[GLOBAL]
version=1.1.4
platform_id=1
appname=yznws
usebililog=true

[LOG]
log_level=0
log_maxsize=512000

[MSG]
packet_chan_size=32767

[GATEMANAGER]
ip=0.0.0.0
port=2026
kcpip=0.0.0.0
kcpport=3026
log=log/gatemanager.log

[GATE]
gateid=0
ip=0.0.0.0
port=2020
kcpip=0.0.0.0
kcpport=3020
log=log/gate.log
online_stat_log=log/online_stat.log
snapshot_interval=3600
conn_ipo_enable=false
connect_gatemanager=false
connect_battleserver=false

[GM]
ip=192.168.20.109
port=4025
log=log/gm.log
snapshot_interval=3600
conn_ipo_enable=false

[GAME]
server_id=1
bip=0.0.0.0
bport=2022
log_dir=log/
mysql_user=root
mysql_pass=gametest
mysql_addr=192.168.20.57:3306
mysql_dbname=go_game

[CENTER]
#db
mysql_user=root
mysql_pass=gametest
mysql_addr=192.168.20.57:3306
mysql_dbname=go_game
#server
bip=0.0.0.0
bport=2023
#log
log=log/center.log

[LOGIN]
rpc_addr=0.0.0.0:8877
log=log/login.log
mysql_user=root
mysql_pass=gametest
mysql_addr=192.168.20.57:3306
mysql_dbname=go_game
need_activation=false

[BEEGOWEB]
mysql_user=root
mysql_pass=gametest
mysql_addr=192.168.20.57:3306
mysql_dbname=go_admin
#cfg_log=log/web.log
#beego_log=log/beego.log
#chat_proxy=
#region_num = 1
httpport=2021
#httpsport=4019
eth_addr=127.0.0.1
static= beegoWeb/static
view= beegoWeb/views
#cert=beegoWeb/cert
#gdtool=false
log=log/beegoWeb.log

[LOGGER]
mysql_user=root
mysql_pass=gametest
mysql_addr=192.168.20.57:3306
mysql_dbname=go_game_log



















#[PLATFORM]
#qa_push=false
#login_verify_url=http://account-api.6waves.com/v1/survivaltactics/token
#iap_url_gp=http://payval-mobile.6waves.com/gp_verify.php
#iap_url_ios=http://payval-mobile.6waves.com/verify.php
#appid_gp=00359956291d81b7
#appid_ios=0015992a95cc39e8
#appid_fb=511980985815779
#appsecret_fb=f4eac9b183c799ea9b967380a64a9bac
#aud_gp=125449141462-77uau189po87f96ft72dnl92oa4jniv5.apps.googleusercontent.com
#mongo_user=
#mongo_pass=
#mongo_addr = 192.168.1.11:28011
#mongo_dbname = platform

[CSV]
gd_csv=/configs/csv/



[CHAT]
#这个ip地址有两处用到
#1、chatserver监听此ip
#2、gs会把这个ip发送给client，client用这个ip和chatserver建立长连接，所以服务器运行时这个ip必须是服务器的ip地址，不能是四个0
ip=192.168.1.11
port=2016
bip=0.0.0.0
bport=2015
domain=127.0.0.1:2061
log=log/chat.log

[ACCOUNT]
mongo_user=
mongo_pass=
mongo_addr=192.168.1.11:28011
mongo_dbname=account



#[GS_TEMP]
#server_id=%
#log=log/gs%.log
#mysql_user=root
#mysql_pass=gametest
#mysql_addr=192.168.20.57:3306
#mysql_dbname=go_game

[MAIL]
server_id=1
bip=0.0.0.0
bport=2025
#log
log=log/mail.log
#db
mysql_user=root
mysql_pass=gametest
mysql_addr=192.168.20.57:3306
mysql_dbname=57_go_mail
#各大类邮箱的最大邮件数量
inbox_num=100
sendbox_num=100
system_num=50
pvp_num=200
pve_num=100

[EVENT]
mongo_user=
mongo_pass=
mongo_addr = 192.168.1.11:28011
mongo_dbname = center
log=log/event.log
rpc_addr=127.0.0.1:8886
base_time=2017-08-11 10:00:00

[ACTIVITY]
mongo_user=
mongo_pass=
mongo_addr = 192.168.1.11:28011
mongo_dbname = activity
port = 2018
ip=192.168.1.11
log=log/activity.log
auto_tick=true


[GM_CMD]
gm_cmd=
log=log/gm.log

[MONGODB_DUMP]
url=http://127.0.0.1:2080/dump
token=go301

[LISTENER]
log=log/listener.log
