// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.9.0
// source: B_BS_Message.proto

package network_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//* GS与GT 连接请求
type BS_ConnectedNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *BS_ConnectedNtf) Reset() {
	*x = BS_ConnectedNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BS_ConnectedNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BS_ConnectedNtf) ProtoMessage() {}

func (x *BS_ConnectedNtf) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BS_ConnectedNtf.ProtoReflect.Descriptor instead.
func (*BS_ConnectedNtf) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{0}
}

func (x *BS_ConnectedNtf) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

//* GT与GS 登录请求
type BS_TestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateServerId  int32 `protobuf:"varint,1,opt,name=gateServerId,proto3" json:"gateServerId,omitempty"`
	UserSessionId int32 `protobuf:"varint,2,opt,name=userSessionId,proto3" json:"userSessionId,omitempty"`
	GateSessionId int32 `protobuf:"varint,3,opt,name=gateSessionId,proto3" json:"gateSessionId,omitempty"`
}

func (x *BS_TestRequest) Reset() {
	*x = BS_TestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BS_TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BS_TestRequest) ProtoMessage() {}

func (x *BS_TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BS_TestRequest.ProtoReflect.Descriptor instead.
func (*BS_TestRequest) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{1}
}

func (x *BS_TestRequest) GetGateServerId() int32 {
	if x != nil {
		return x.GateServerId
	}
	return 0
}

func (x *BS_TestRequest) GetUserSessionId() int32 {
	if x != nil {
		return x.UserSessionId
	}
	return 0
}

func (x *BS_TestRequest) GetGateSessionId() int32 {
	if x != nil {
		return x.GateSessionId
	}
	return 0
}

type BS_TestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result        Result `protobuf:"varint,1,opt,name=result,proto3,enum=network.message.Result" json:"result,omitempty"`
	GateServerId  int32  `protobuf:"varint,2,opt,name=gateServerId,proto3" json:"gateServerId,omitempty"`
	UserSessionId int32  `protobuf:"varint,3,opt,name=userSessionId,proto3" json:"userSessionId,omitempty"`
	GateSessionId int32  `protobuf:"varint,4,opt,name=gateSessionId,proto3" json:"gateSessionId,omitempty"`
}

func (x *BS_TestResponse) Reset() {
	*x = BS_TestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BS_TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BS_TestResponse) ProtoMessage() {}

func (x *BS_TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BS_TestResponse.ProtoReflect.Descriptor instead.
func (*BS_TestResponse) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{2}
}

func (x *BS_TestResponse) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_SUCCESS
}

func (x *BS_TestResponse) GetGateServerId() int32 {
	if x != nil {
		return x.GateServerId
	}
	return 0
}

func (x *BS_TestResponse) GetUserSessionId() int32 {
	if x != nil {
		return x.UserSessionId
	}
	return 0
}

func (x *BS_TestResponse) GetGateSessionId() int32 {
	if x != nil {
		return x.GateSessionId
	}
	return 0
}

//*房间战斗开始
type CS2B_RoomBattleStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int32           `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	InstanceId int32           `protobuf:"varint,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	CaptainId  uint64          `protobuf:"varint,3,opt,name=captainId,proto3" json:"captainId,omitempty"` //队长roleid
	Roles      []*RoomRoleData `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	LevelLimit int32           `protobuf:"varint,5,opt,name=levelLimit,proto3" json:"levelLimit,omitempty"` //等级限制
}

func (x *CS2B_RoomBattleStart) Reset() {
	*x = CS2B_RoomBattleStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2B_RoomBattleStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2B_RoomBattleStart) ProtoMessage() {}

func (x *CS2B_RoomBattleStart) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2B_RoomBattleStart.ProtoReflect.Descriptor instead.
func (*CS2B_RoomBattleStart) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{3}
}

func (x *CS2B_RoomBattleStart) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CS2B_RoomBattleStart) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *CS2B_RoomBattleStart) GetCaptainId() uint64 {
	if x != nil {
		return x.CaptainId
	}
	return 0
}

func (x *CS2B_RoomBattleStart) GetRoles() []*RoomRoleData {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *CS2B_RoomBattleStart) GetLevelLimit() int32 {
	if x != nil {
		return x.LevelLimit
	}
	return 0
}

type RoleDataGo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64          `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	HeroId uint64          `protobuf:"varint,2,opt,name=heroId,proto3" json:"heroId,omitempty"`
	Values map[int32]int32 `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *RoleDataGo) Reset() {
	*x = RoleDataGo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDataGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDataGo) ProtoMessage() {}

func (x *RoleDataGo) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDataGo.ProtoReflect.Descriptor instead.
func (*RoleDataGo) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{4}
}

func (x *RoleDataGo) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleDataGo) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *RoleDataGo) GetValues() map[int32]int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type B2CS_PvpResultGo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int32         `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	LevelId    int32         `protobuf:"varint,2,opt,name=levelId,proto3" json:"levelId,omitempty"` //关卡ID
	RoleDataGo []*RoleDataGo `protobuf:"bytes,3,rep,name=roleDataGo,proto3" json:"roleDataGo,omitempty"`
}

func (x *B2CS_PvpResultGo) Reset() {
	*x = B2CS_PvpResultGo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B2CS_PvpResultGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B2CS_PvpResultGo) ProtoMessage() {}

func (x *B2CS_PvpResultGo) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B2CS_PvpResultGo.ProtoReflect.Descriptor instead.
func (*B2CS_PvpResultGo) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{5}
}

func (x *B2CS_PvpResultGo) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *B2CS_PvpResultGo) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *B2CS_PvpResultGo) GetRoleDataGo() []*RoleDataGo {
	if x != nil {
		return x.RoleDataGo
	}
	return nil
}

type CS2B_PvpResultGo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CS2B_PvpResultGo) Reset() {
	*x = CS2B_PvpResultGo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2B_PvpResultGo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2B_PvpResultGo) ProtoMessage() {}

func (x *CS2B_PvpResultGo) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2B_PvpResultGo.ProtoReflect.Descriptor instead.
func (*CS2B_PvpResultGo) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{6}
}

type B2CS_GetPvpResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *B2CS_GetPvpResult) Reset() {
	*x = B2CS_GetPvpResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B2CS_GetPvpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B2CS_GetPvpResult) ProtoMessage() {}

func (x *B2CS_GetPvpResult) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B2CS_GetPvpResult.ProtoReflect.Descriptor instead.
func (*B2CS_GetPvpResult) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{7}
}

func (x *B2CS_GetPvpResult) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type CS2B_GetPvpResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId  int32           `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	LevelId int32           `protobuf:"varint,2,opt,name=levelId,proto3" json:"levelId,omitempty"`
	Values  map[int32]int32 `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *CS2B_GetPvpResult) Reset() {
	*x = CS2B_GetPvpResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2B_GetPvpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2B_GetPvpResult) ProtoMessage() {}

func (x *CS2B_GetPvpResult) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2B_GetPvpResult.ProtoReflect.Descriptor instead.
func (*CS2B_GetPvpResult) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{8}
}

func (x *CS2B_GetPvpResult) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CS2B_GetPvpResult) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *CS2B_GetPvpResult) GetValues() map[int32]int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type B2CS_UpdateRoomData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int32  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"` //必需
	RoleId uint64 `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"` //非必需 直接销毁房间时可为0
}

func (x *B2CS_UpdateRoomData) Reset() {
	*x = B2CS_UpdateRoomData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B2CS_UpdateRoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B2CS_UpdateRoomData) ProtoMessage() {}

func (x *B2CS_UpdateRoomData) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B2CS_UpdateRoomData.ProtoReflect.Descriptor instead.
func (*B2CS_UpdateRoomData) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{9}
}

func (x *B2CS_UpdateRoomData) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *B2CS_UpdateRoomData) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type CS2B_UpdateRoomData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CS2B_UpdateRoomData) Reset() {
	*x = CS2B_UpdateRoomData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_BS_Message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2B_UpdateRoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2B_UpdateRoomData) ProtoMessage() {}

func (x *CS2B_UpdateRoomData) ProtoReflect() protoreflect.Message {
	mi := &file_B_BS_Message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2B_UpdateRoomData.ProtoReflect.Descriptor instead.
func (*CS2B_UpdateRoomData) Descriptor() ([]byte, []int) {
	return file_B_BS_Message_proto_rawDescGZIP(), []int{10}
}

var File_B_BS_Message_proto protoreflect.FileDescriptor

var file_B_BS_Message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x42, 0x5f, 0x42, 0x53, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0f, 0x42, 0x53, 0x5f, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x4e, 0x74, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x42, 0x53, 0x5f, 0x54, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x67,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x75,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xb2, 0x01, 0x0a, 0x0f, 0x42, 0x53, 0x5f, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x67,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xc1, 0x01, 0x0a,
	0x14, 0x43, 0x53, 0x32, 0x42, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x61, 0x70, 0x74, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x63, 0x61, 0x70, 0x74, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x72,
	0x6f, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0xb8, 0x01, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x47, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12,
	0x3f, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x47, 0x6f, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x1a, 0x39, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x81, 0x01, 0x0a, 0x10,
	0x42, 0x32, 0x43, 0x53, 0x5f, 0x50, 0x76, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x47, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x49, 0x64, 0x12, 0x3b, 0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x47, 0x6f,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x47, 0x6f, 0x52, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x47, 0x6f, 0x22,
	0x12, 0x0a, 0x10, 0x43, 0x53, 0x32, 0x42, 0x5f, 0x50, 0x76, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x47, 0x6f, 0x22, 0x2b, 0x0a, 0x11, 0x42, 0x32, 0x43, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x50,
	0x76, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x22, 0xc8, 0x01, 0x0a, 0x11, 0x43, 0x53, 0x32, 0x42, 0x5f, 0x47, 0x65, 0x74, 0x50, 0x76, 0x70,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x46, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x53, 0x32, 0x42, 0x5f,
	0x47, 0x65, 0x74, 0x50, 0x76, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x1a, 0x39, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x45, 0x0a, 0x13, 0x42,
	0x32, 0x43, 0x53, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x53, 0x32, 0x42, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_B_BS_Message_proto_rawDescOnce sync.Once
	file_B_BS_Message_proto_rawDescData = file_B_BS_Message_proto_rawDesc
)

func file_B_BS_Message_proto_rawDescGZIP() []byte {
	file_B_BS_Message_proto_rawDescOnce.Do(func() {
		file_B_BS_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_B_BS_Message_proto_rawDescData)
	})
	return file_B_BS_Message_proto_rawDescData
}

var file_B_BS_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_B_BS_Message_proto_goTypes = []interface{}{
	(*BS_ConnectedNtf)(nil),      // 0: network.message.BS_ConnectedNtf
	(*BS_TestRequest)(nil),       // 1: network.message.BS_TestRequest
	(*BS_TestResponse)(nil),      // 2: network.message.BS_TestResponse
	(*CS2B_RoomBattleStart)(nil), // 3: network.message.CS2B_RoomBattleStart
	(*RoleDataGo)(nil),           // 4: network.message.RoleDataGo
	(*B2CS_PvpResultGo)(nil),     // 5: network.message.B2CS_PvpResultGo
	(*CS2B_PvpResultGo)(nil),     // 6: network.message.CS2B_PvpResultGo
	(*B2CS_GetPvpResult)(nil),    // 7: network.message.B2CS_GetPvpResult
	(*CS2B_GetPvpResult)(nil),    // 8: network.message.CS2B_GetPvpResult
	(*B2CS_UpdateRoomData)(nil),  // 9: network.message.B2CS_UpdateRoomData
	(*CS2B_UpdateRoomData)(nil),  // 10: network.message.CS2B_UpdateRoomData
	nil,                          // 11: network.message.RoleDataGo.ValuesEntry
	nil,                          // 12: network.message.CS2B_GetPvpResult.ValuesEntry
	(Result)(0),                  // 13: network.message.Result
	(*RoomRoleData)(nil),         // 14: network.message.RoomRoleData
}
var file_B_BS_Message_proto_depIdxs = []int32{
	13, // 0: network.message.BS_TestResponse.result:type_name -> network.message.Result
	14, // 1: network.message.CS2B_RoomBattleStart.roles:type_name -> network.message.RoomRoleData
	11, // 2: network.message.RoleDataGo.values:type_name -> network.message.RoleDataGo.ValuesEntry
	4,  // 3: network.message.B2CS_PvpResultGo.roleDataGo:type_name -> network.message.RoleDataGo
	12, // 4: network.message.CS2B_GetPvpResult.values:type_name -> network.message.CS2B_GetPvpResult.ValuesEntry
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_B_BS_Message_proto_init() }
func file_B_BS_Message_proto_init() {
	if File_B_BS_Message_proto != nil {
		return
	}
	file_BaseInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_B_BS_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BS_ConnectedNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BS_TestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BS_TestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2B_RoomBattleStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleDataGo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B2CS_PvpResultGo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2B_PvpResultGo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B2CS_GetPvpResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2B_GetPvpResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B2CS_UpdateRoomData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_BS_Message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2B_UpdateRoomData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_B_BS_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_B_BS_Message_proto_goTypes,
		DependencyIndexes: file_B_BS_Message_proto_depIdxs,
		MessageInfos:      file_B_BS_Message_proto_msgTypes,
	}.Build()
	File_B_BS_Message_proto = out.File
	file_B_BS_Message_proto_rawDesc = nil
	file_B_BS_Message_proto_goTypes = nil
	file_B_BS_Message_proto_depIdxs = nil
}
