// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.9.0
// source: B_CN_Message.proto

package network_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//========================================================================
// 与中心服相关的消息
//========================================================================
type GS_AddUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GsId     int32  `protobuf:"varint,1,opt,name=gsId,proto3" json:"gsId,omitempty"`
	UserId   uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
}

func (x *GS_AddUser) Reset() {
	*x = GS_AddUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_CN_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GS_AddUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GS_AddUser) ProtoMessage() {}

func (x *GS_AddUser) ProtoReflect() protoreflect.Message {
	mi := &file_B_CN_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GS_AddUser.ProtoReflect.Descriptor instead.
func (*GS_AddUser) Descriptor() ([]byte, []int) {
	return file_B_CN_Message_proto_rawDescGZIP(), []int{0}
}

func (x *GS_AddUser) GetGsId() int32 {
	if x != nil {
		return x.GsId
	}
	return 0
}

func (x *GS_AddUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GS_AddUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GS_DeleteUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GsId   int32  `protobuf:"varint,1,opt,name=gsId,proto3" json:"gsId,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GS_DeleteUser) Reset() {
	*x = GS_DeleteUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_CN_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GS_DeleteUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GS_DeleteUser) ProtoMessage() {}

func (x *GS_DeleteUser) ProtoReflect() protoreflect.Message {
	mi := &file_B_CN_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GS_DeleteUser.ProtoReflect.Descriptor instead.
func (*GS_DeleteUser) Descriptor() ([]byte, []int) {
	return file_B_CN_Message_proto_rawDescGZIP(), []int{1}
}

func (x *GS_DeleteUser) GetGsId() int32 {
	if x != nil {
		return x.GsId
	}
	return 0
}

func (x *GS_DeleteUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GS_UseNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number     string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	NumberType int32  `protobuf:"varint,3,opt,name=numberType,proto3" json:"numberType,omitempty"`
}

func (x *GS_UseNumberRequest) Reset() {
	*x = GS_UseNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_CN_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GS_UseNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GS_UseNumberRequest) ProtoMessage() {}

func (x *GS_UseNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_CN_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GS_UseNumberRequest.ProtoReflect.Descriptor instead.
func (*GS_UseNumberRequest) Descriptor() ([]byte, []int) {
	return file_B_CN_Message_proto_rawDescGZIP(), []int{2}
}

func (x *GS_UseNumberRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GS_UseNumberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GS_UseNumberRequest) GetNumberType() int32 {
	if x != nil {
		return x.NumberType
	}
	return 0
}

type GS_UseNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetState int32  `protobuf:"varint,1,opt,name=retState,proto3" json:"retState,omitempty"` // 0.未找到该码/码已过期；1.可以使用；2.码已被使用
	UserId   string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GS_UseNumberResponse) Reset() {
	*x = GS_UseNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_CN_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GS_UseNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GS_UseNumberResponse) ProtoMessage() {}

func (x *GS_UseNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_CN_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GS_UseNumberResponse.ProtoReflect.Descriptor instead.
func (*GS_UseNumberResponse) Descriptor() ([]byte, []int) {
	return file_B_CN_Message_proto_rawDescGZIP(), []int{3}
}

func (x *GS_UseNumberResponse) GetRetState() int32 {
	if x != nil {
		return x.RetState
	}
	return 0
}

func (x *GS_UseNumberResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GM_CreateNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId  int64  `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`   //beegoweb用的字段
	NumberType int32  `protobuf:"varint,2,opt,name=numberType,proto3" json:"numberType,omitempty"` // 码类型，目前暂定 1为激活码，2为礼包码
	ScrapTime  int32  `protobuf:"varint,3,opt,name=scrapTime,proto3" json:"scrapTime,omitempty"`   // 失效时间，单位为秒，0为永远有效
	Unique     int32  `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`         // 是否唯一，唯一则只能被1个玩家使用
	Param      string `protobuf:"bytes,5,opt,name=param,proto3" json:"param,omitempty"`            // 包含礼包、互斥组等信息的字符串
	Num        int32  `protobuf:"varint,6,opt,name=num,proto3" json:"num,omitempty"`               // 生成数量
	ConnectId  int32  `protobuf:"varint,7,opt,name=connectId,proto3" json:"connectId,omitempty"`
}

func (x *GM_CreateNumberRequest) Reset() {
	*x = GM_CreateNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_CN_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GM_CreateNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GM_CreateNumberRequest) ProtoMessage() {}

func (x *GM_CreateNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_CN_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GM_CreateNumberRequest.ProtoReflect.Descriptor instead.
func (*GM_CreateNumberRequest) Descriptor() ([]byte, []int) {
	return file_B_CN_Message_proto_rawDescGZIP(), []int{4}
}

func (x *GM_CreateNumberRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GM_CreateNumberRequest) GetNumberType() int32 {
	if x != nil {
		return x.NumberType
	}
	return 0
}

func (x *GM_CreateNumberRequest) GetScrapTime() int32 {
	if x != nil {
		return x.ScrapTime
	}
	return 0
}

func (x *GM_CreateNumberRequest) GetUnique() int32 {
	if x != nil {
		return x.Unique
	}
	return 0
}

func (x *GM_CreateNumberRequest) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *GM_CreateNumberRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GM_CreateNumberRequest) GetConnectId() int32 {
	if x != nil {
		return x.ConnectId
	}
	return 0
}

type GM_CreateNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId  int64    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"` //beegoweb用的字段
	ErrCode    int32    `protobuf:"varint,2,opt,name=errCode,proto3" json:"errCode,omitempty"`     //beegoweb用的字段
	NumberList []string `protobuf:"bytes,3,rep,name=numberList,proto3" json:"numberList,omitempty"`
	Num        int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"` // 成功生成的量
	ConnectId  int32    `protobuf:"varint,5,opt,name=connectId,proto3" json:"connectId,omitempty"`
}

func (x *GM_CreateNumberResponse) Reset() {
	*x = GM_CreateNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_CN_Message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GM_CreateNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GM_CreateNumberResponse) ProtoMessage() {}

func (x *GM_CreateNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_CN_Message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GM_CreateNumberResponse.ProtoReflect.Descriptor instead.
func (*GM_CreateNumberResponse) Descriptor() ([]byte, []int) {
	return file_B_CN_Message_proto_rawDescGZIP(), []int{5}
}

func (x *GM_CreateNumberResponse) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GM_CreateNumberResponse) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GM_CreateNumberResponse) GetNumberList() []string {
	if x != nil {
		return x.NumberList
	}
	return nil
}

func (x *GM_CreateNumberResponse) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GM_CreateNumberResponse) GetConnectId() int32 {
	if x != nil {
		return x.ConnectId
	}
	return 0
}

var File_B_CN_Message_proto protoreflect.FileDescriptor

var file_B_CN_Message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x42, 0x5f, 0x43, 0x4e, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x54, 0x0a, 0x0a, 0x47, 0x53, 0x5f, 0x41, 0x64, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x67, 0x73, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x0d, 0x47,
	0x53, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x67, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67, 0x73, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x65, 0x0a, 0x13, 0x47, 0x53, 0x5f, 0x55,
	0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x4a, 0x0a, 0x14, 0x47, 0x53, 0x5f, 0x55, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xd2, 0x01, 0x0a, 0x16,
	0x47, 0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x63, 0x72, 0x61, 0x70, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x63, 0x72, 0x61, 0x70, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x22, 0xa1, 0x01, 0x0a, 0x17, 0x47, 0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_B_CN_Message_proto_rawDescOnce sync.Once
	file_B_CN_Message_proto_rawDescData = file_B_CN_Message_proto_rawDesc
)

func file_B_CN_Message_proto_rawDescGZIP() []byte {
	file_B_CN_Message_proto_rawDescOnce.Do(func() {
		file_B_CN_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_B_CN_Message_proto_rawDescData)
	})
	return file_B_CN_Message_proto_rawDescData
}

var file_B_CN_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_B_CN_Message_proto_goTypes = []interface{}{
	(*GS_AddUser)(nil),              // 0: network.message.GS_AddUser
	(*GS_DeleteUser)(nil),           // 1: network.message.GS_DeleteUser
	(*GS_UseNumberRequest)(nil),     // 2: network.message.GS_UseNumberRequest
	(*GS_UseNumberResponse)(nil),    // 3: network.message.GS_UseNumberResponse
	(*GM_CreateNumberRequest)(nil),  // 4: network.message.GM_CreateNumberRequest
	(*GM_CreateNumberResponse)(nil), // 5: network.message.GM_CreateNumberResponse
}
var file_B_CN_Message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_B_CN_Message_proto_init() }
func file_B_CN_Message_proto_init() {
	if File_B_CN_Message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_B_CN_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GS_AddUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_CN_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GS_DeleteUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_CN_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GS_UseNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_CN_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GS_UseNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_CN_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GM_CreateNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_CN_Message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GM_CreateNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_B_CN_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_B_CN_Message_proto_goTypes,
		DependencyIndexes: file_B_CN_Message_proto_depIdxs,
		MessageInfos:      file_B_CN_Message_proto_msgTypes,
	}.Build()
	File_B_CN_Message_proto = out.File
	file_B_CN_Message_proto_rawDesc = nil
	file_B_CN_Message_proto_goTypes = nil
	file_B_CN_Message_proto_depIdxs = nil
}
