// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.9.0
// source: B_Communication.proto

package network_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//* GS与GT单个玩家打包信息
type B_PktUserMsgNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId    uint64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	SessionId int32  `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Head      string `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	Body      []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TimeStamp int64  `protobuf:"varint,5,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *B_PktUserMsgNtf) Reset() {
	*x = B_PktUserMsgNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_Communication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B_PktUserMsgNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B_PktUserMsgNtf) ProtoMessage() {}

func (x *B_PktUserMsgNtf) ProtoReflect() protoreflect.Message {
	mi := &file_B_Communication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B_PktUserMsgNtf.ProtoReflect.Descriptor instead.
func (*B_PktUserMsgNtf) Descriptor() ([]byte, []int) {
	return file_B_Communication_proto_rawDescGZIP(), []int{0}
}

func (x *B_PktUserMsgNtf) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *B_PktUserMsgNtf) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *B_PktUserMsgNtf) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *B_PktUserMsgNtf) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *B_PktUserMsgNtf) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

//* 玩家Session信息
type B_UserSessionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId     uint64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	SessionId  int32  `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	ServerId   int32  `protobuf:"varint,3,opt,name=serverId,proto3" json:"serverId,omitempty"`
	AllianceId int32  `protobuf:"varint,4,opt,name=allianceId,proto3" json:"allianceId,omitempty"`
}

func (x *B_UserSessionInfo) Reset() {
	*x = B_UserSessionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_Communication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B_UserSessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B_UserSessionInfo) ProtoMessage() {}

func (x *B_UserSessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_B_Communication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B_UserSessionInfo.ProtoReflect.Descriptor instead.
func (*B_UserSessionInfo) Descriptor() ([]byte, []int) {
	return file_B_Communication_proto_rawDescGZIP(), []int{1}
}

func (x *B_UserSessionInfo) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *B_UserSessionInfo) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *B_UserSessionInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *B_UserSessionInfo) GetAllianceId() int32 {
	if x != nil {
		return x.AllianceId
	}
	return 0
}

//* 全局服务器退出通知
type B_ServerQuitNTF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *B_ServerQuitNTF) Reset() {
	*x = B_ServerQuitNTF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_Communication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B_ServerQuitNTF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B_ServerQuitNTF) ProtoMessage() {}

func (x *B_ServerQuitNTF) ProtoReflect() protoreflect.Message {
	mi := &file_B_Communication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B_ServerQuitNTF.ProtoReflect.Descriptor instead.
func (*B_ServerQuitNTF) Descriptor() ([]byte, []int) {
	return file_B_Communication_proto_rawDescGZIP(), []int{2}
}

//* 新服务器退出通知
type B_NewServerQuit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *B_NewServerQuit) Reset() {
	*x = B_NewServerQuit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_Communication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B_NewServerQuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B_NewServerQuit) ProtoMessage() {}

func (x *B_NewServerQuit) ProtoReflect() protoreflect.Message {
	mi := &file_B_Communication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B_NewServerQuit.ProtoReflect.Descriptor instead.
func (*B_NewServerQuit) Descriptor() ([]byte, []int) {
	return file_B_Communication_proto_rawDescGZIP(), []int{3}
}

func (x *B_NewServerQuit) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type HeartBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_Communication_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_Communication_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_B_Communication_proto_rawDescGZIP(), []int{4}
}

type HeartBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_Communication_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_Communication_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_B_Communication_proto_rawDescGZIP(), []int{5}
}

//* 与gatemanager之间的心跳
type GateManagerHeartBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectNum           int32  `protobuf:"varint,1,opt,name=connectNum,proto3" json:"connectNum,omitempty"`                    // gate目前与客户端的连接数
	ClientConnectAddress string `protobuf:"bytes,2,opt,name=clientConnectAddress,proto3" json:"clientConnectAddress,omitempty"` // 客戶端连接gate的地址
}

func (x *GateManagerHeartBeatRequest) Reset() {
	*x = GateManagerHeartBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_Communication_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateManagerHeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateManagerHeartBeatRequest) ProtoMessage() {}

func (x *GateManagerHeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_Communication_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateManagerHeartBeatRequest.ProtoReflect.Descriptor instead.
func (*GateManagerHeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_B_Communication_proto_rawDescGZIP(), []int{6}
}

func (x *GateManagerHeartBeatRequest) GetConnectNum() int32 {
	if x != nil {
		return x.ConnectNum
	}
	return 0
}

func (x *GateManagerHeartBeatRequest) GetClientConnectAddress() string {
	if x != nil {
		return x.ClientConnectAddress
	}
	return ""
}

type GateManagerHeartBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GateManagerHeartBeatResponse) Reset() {
	*x = GateManagerHeartBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_Communication_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateManagerHeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateManagerHeartBeatResponse) ProtoMessage() {}

func (x *GateManagerHeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_Communication_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateManagerHeartBeatResponse.ProtoReflect.Descriptor instead.
func (*GateManagerHeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_B_Communication_proto_rawDescGZIP(), []int{7}
}

var File_B_Communication_proto protoreflect.FileDescriptor

var file_B_Communication_proto_rawDesc = []byte{
	0x0a, 0x15, 0x42, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0f, 0x42, 0x5f, 0x50,
	0x6b, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x4e, 0x74, 0x66, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x85, 0x01, 0x0a, 0x11, 0x42, 0x5f, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x22, 0x11, 0x0a, 0x0f, 0x42, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x51, 0x75, 0x69, 0x74,
	0x4e, 0x54, 0x46, 0x22, 0x2d, 0x0a, 0x0f, 0x42, 0x5f, 0x4e, 0x65, 0x77, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x51, 0x75, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x71, 0x0a, 0x1b, 0x47,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x32, 0x0a, 0x14, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1e,
	0x0a, 0x1c, 0x47, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13,
	0x5a, 0x11, 0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_B_Communication_proto_rawDescOnce sync.Once
	file_B_Communication_proto_rawDescData = file_B_Communication_proto_rawDesc
)

func file_B_Communication_proto_rawDescGZIP() []byte {
	file_B_Communication_proto_rawDescOnce.Do(func() {
		file_B_Communication_proto_rawDescData = protoimpl.X.CompressGZIP(file_B_Communication_proto_rawDescData)
	})
	return file_B_Communication_proto_rawDescData
}

var file_B_Communication_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_B_Communication_proto_goTypes = []interface{}{
	(*B_PktUserMsgNtf)(nil),              // 0: network.message.B_PktUserMsgNtf
	(*B_UserSessionInfo)(nil),            // 1: network.message.B_UserSessionInfo
	(*B_ServerQuitNTF)(nil),              // 2: network.message.B_ServerQuitNTF
	(*B_NewServerQuit)(nil),              // 3: network.message.B_NewServerQuit
	(*HeartBeatRequest)(nil),             // 4: network.message.HeartBeatRequest
	(*HeartBeatResponse)(nil),            // 5: network.message.HeartBeatResponse
	(*GateManagerHeartBeatRequest)(nil),  // 6: network.message.GateManagerHeartBeatRequest
	(*GateManagerHeartBeatResponse)(nil), // 7: network.message.GateManagerHeartBeatResponse
}
var file_B_Communication_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_B_Communication_proto_init() }
func file_B_Communication_proto_init() {
	if File_B_Communication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_B_Communication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B_PktUserMsgNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_Communication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B_UserSessionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_Communication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B_ServerQuitNTF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_Communication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B_NewServerQuit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_Communication_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_Communication_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_Communication_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateManagerHeartBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_Communication_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateManagerHeartBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_B_Communication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_B_Communication_proto_goTypes,
		DependencyIndexes: file_B_Communication_proto_depIdxs,
		MessageInfos:      file_B_Communication_proto_msgTypes,
	}.Build()
	File_B_Communication_proto = out.File
	file_B_Communication_proto_rawDesc = nil
	file_B_Communication_proto_goTypes = nil
	file_B_Communication_proto_depIdxs = nil
}
