// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.9.0
// source: B_GS_Message.proto

package network_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//* GS与GT 连接请求
type GS_ConnectedNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *GS_ConnectedNtf) Reset() {
	*x = GS_ConnectedNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GS_ConnectedNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GS_ConnectedNtf) ProtoMessage() {}

func (x *GS_ConnectedNtf) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GS_ConnectedNtf.ProtoReflect.Descriptor instead.
func (*GS_ConnectedNtf) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{0}
}

func (x *GS_ConnectedNtf) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

//* GT与GS 登录请求
type GS_LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account       string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Gold          int32  `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	GateSessionId int32  `protobuf:"varint,3,opt,name=gateSessionId,proto3" json:"gateSessionId,omitempty"`
	UserSessionId int32  `protobuf:"varint,4,opt,name=userSessionId,proto3" json:"userSessionId,omitempty"`
}

func (x *GS_LoginRequest) Reset() {
	*x = GS_LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GS_LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GS_LoginRequest) ProtoMessage() {}

func (x *GS_LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GS_LoginRequest.ProtoReflect.Descriptor instead.
func (*GS_LoginRequest) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{1}
}

func (x *GS_LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GS_LoginRequest) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GS_LoginRequest) GetGateSessionId() int32 {
	if x != nil {
		return x.GateSessionId
	}
	return 0
}

func (x *GS_LoginRequest) GetUserSessionId() int32 {
	if x != nil {
		return x.UserSessionId
	}
	return 0
}

type GS_LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result        Result `protobuf:"varint,1,opt,name=result,proto3,enum=network.message.Result" json:"result,omitempty"`
	Account       string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Gold          int32  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	GateSessionId int32  `protobuf:"varint,4,opt,name=gateSessionId,proto3" json:"gateSessionId,omitempty"`
	UserSessionId int32  `protobuf:"varint,5,opt,name=userSessionId,proto3" json:"userSessionId,omitempty"`
}

func (x *GS_LoginResponse) Reset() {
	*x = GS_LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GS_LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GS_LoginResponse) ProtoMessage() {}

func (x *GS_LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GS_LoginResponse.ProtoReflect.Descriptor instead.
func (*GS_LoginResponse) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{2}
}

func (x *GS_LoginResponse) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_SUCCESS
}

func (x *GS_LoginResponse) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GS_LoginResponse) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GS_LoginResponse) GetGateSessionId() int32 {
	if x != nil {
		return x.GateSessionId
	}
	return 0
}

func (x *GS_LoginResponse) GetUserSessionId() int32 {
	if x != nil {
		return x.UserSessionId
	}
	return 0
}

//* GS与GT通讯踢掉某个玩家
type GS_KickOutNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionInfo *B_UserSessionInfo `protobuf:"bytes,1,opt,name=userSessionInfo,proto3" json:"userSessionInfo,omitempty"`
}

func (x *GS_KickOutNtf) Reset() {
	*x = GS_KickOutNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GS_KickOutNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GS_KickOutNtf) ProtoMessage() {}

func (x *GS_KickOutNtf) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GS_KickOutNtf.ProtoReflect.Descriptor instead.
func (*GS_KickOutNtf) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{3}
}

func (x *GS_KickOutNtf) GetUserSessionInfo() *B_UserSessionInfo {
	if x != nil {
		return x.UserSessionInfo
	}
	return nil
}

type G2CS_GetBattleRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roleid uint64 `protobuf:"varint,1,opt,name=roleid,proto3" json:"roleid,omitempty"`
	Roomid int32  `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"` //获取全部发0
}

func (x *G2CS_GetBattleRoom) Reset() {
	*x = G2CS_GetBattleRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2CS_GetBattleRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2CS_GetBattleRoom) ProtoMessage() {}

func (x *G2CS_GetBattleRoom) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2CS_GetBattleRoom.ProtoReflect.Descriptor instead.
func (*G2CS_GetBattleRoom) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{4}
}

func (x *G2CS_GetBattleRoom) GetRoleid() uint64 {
	if x != nil {
		return x.Roleid
	}
	return 0
}

func (x *G2CS_GetBattleRoom) GetRoomid() int32 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

type CS2G_GetBattleRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roleid uint64        `protobuf:"varint,1,opt,name=roleid,proto3" json:"roleid,omitempty"`
	Rrd    []*BattleRoom `protobuf:"bytes,2,rep,name=rrd,proto3" json:"rrd,omitempty"` //获取全部发0
}

func (x *CS2G_GetBattleRoom) Reset() {
	*x = CS2G_GetBattleRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2G_GetBattleRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2G_GetBattleRoom) ProtoMessage() {}

func (x *CS2G_GetBattleRoom) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2G_GetBattleRoom.ProtoReflect.Descriptor instead.
func (*CS2G_GetBattleRoom) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{5}
}

func (x *CS2G_GetBattleRoom) GetRoleid() uint64 {
	if x != nil {
		return x.Roleid
	}
	return 0
}

func (x *CS2G_GetBattleRoom) GetRrd() []*BattleRoom {
	if x != nil {
		return x.Rrd
	}
	return nil
}

type G2CS_OpenBattleRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId     uint64        `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Roomid     int32         `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`         //创建房间时发0
	Roomtype   int32         `protobuf:"varint,3,opt,name=roomtype,proto3" json:"roomtype,omitempty"`     //0公开 1私有 进入他人房间发0
	Levellimit int32         `protobuf:"varint,4,opt,name=levellimit,proto3" json:"levellimit,omitempty"` //等级限制 0不限制  进入他人房间发0
	Roomname   string        `protobuf:"bytes,5,opt,name=roomname,proto3" json:"roomname,omitempty"`      //房间名称
	Instanceid int32         `protobuf:"varint,6,opt,name=instanceid,proto3" json:"instanceid,omitempty"`
	RoleData   *RoomRoleData `protobuf:"bytes,7,opt,name=RoleData,proto3" json:"RoleData,omitempty"`
}

func (x *G2CS_OpenBattleRoom) Reset() {
	*x = G2CS_OpenBattleRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2CS_OpenBattleRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2CS_OpenBattleRoom) ProtoMessage() {}

func (x *G2CS_OpenBattleRoom) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2CS_OpenBattleRoom.ProtoReflect.Descriptor instead.
func (*G2CS_OpenBattleRoom) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{6}
}

func (x *G2CS_OpenBattleRoom) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *G2CS_OpenBattleRoom) GetRoomid() int32 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *G2CS_OpenBattleRoom) GetRoomtype() int32 {
	if x != nil {
		return x.Roomtype
	}
	return 0
}

func (x *G2CS_OpenBattleRoom) GetLevellimit() int32 {
	if x != nil {
		return x.Levellimit
	}
	return 0
}

func (x *G2CS_OpenBattleRoom) GetRoomname() string {
	if x != nil {
		return x.Roomname
	}
	return ""
}

func (x *G2CS_OpenBattleRoom) GetInstanceid() int32 {
	if x != nil {
		return x.Instanceid
	}
	return 0
}

func (x *G2CS_OpenBattleRoom) GetRoleData() *RoomRoleData {
	if x != nil {
		return x.RoleData
	}
	return nil
}

type CS2G_OpenBattleRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64      `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Isok   bool        `protobuf:"varint,2,opt,name=isok,proto3" json:"isok,omitempty"`
	Baroom *BattleRoom `protobuf:"bytes,3,opt,name=baroom,proto3" json:"baroom,omitempty"`
}

func (x *CS2G_OpenBattleRoom) Reset() {
	*x = CS2G_OpenBattleRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2G_OpenBattleRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2G_OpenBattleRoom) ProtoMessage() {}

func (x *CS2G_OpenBattleRoom) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2G_OpenBattleRoom.ProtoReflect.Descriptor instead.
func (*CS2G_OpenBattleRoom) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{7}
}

func (x *CS2G_OpenBattleRoom) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CS2G_OpenBattleRoom) GetIsok() bool {
	if x != nil {
		return x.Isok
	}
	return false
}

func (x *CS2G_OpenBattleRoom) GetBaroom() *BattleRoom {
	if x != nil {
		return x.Baroom
	}
	return nil
}

type G2CS_OutBattleRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId    uint64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoomId    int32  `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	OutRoleId uint64 `protobuf:"varint,3,opt,name=outRoleId,proto3" json:"outRoleId,omitempty"`
}

func (x *G2CS_OutBattleRoom) Reset() {
	*x = G2CS_OutBattleRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2CS_OutBattleRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2CS_OutBattleRoom) ProtoMessage() {}

func (x *G2CS_OutBattleRoom) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2CS_OutBattleRoom.ProtoReflect.Descriptor instead.
func (*G2CS_OutBattleRoom) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{8}
}

func (x *G2CS_OutBattleRoom) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *G2CS_OutBattleRoom) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *G2CS_OutBattleRoom) GetOutRoleId() uint64 {
	if x != nil {
		return x.OutRoleId
	}
	return 0
}

type G2CS_StartBattleRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId    uint64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Roomid    int32  `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
	StartType int32  `protobuf:"varint,3,opt,name=startType,proto3" json:"startType,omitempty"` //1准备 2开始
}

func (x *G2CS_StartBattleRoom) Reset() {
	*x = G2CS_StartBattleRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2CS_StartBattleRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2CS_StartBattleRoom) ProtoMessage() {}

func (x *G2CS_StartBattleRoom) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2CS_StartBattleRoom.ProtoReflect.Descriptor instead.
func (*G2CS_StartBattleRoom) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{9}
}

func (x *G2CS_StartBattleRoom) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *G2CS_StartBattleRoom) GetRoomid() int32 {
	if x != nil {
		return x.Roomid
	}
	return 0
}

func (x *G2CS_StartBattleRoom) GetStartType() int32 {
	if x != nil {
		return x.StartType
	}
	return 0
}

type CS2G_StartBattleRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId    uint64      `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Isok      bool        `protobuf:"varint,2,opt,name=isok,proto3" json:"isok,omitempty"`
	Baroom    *BattleRoom `protobuf:"bytes,3,opt,name=baroom,proto3" json:"baroom,omitempty"`
	StartType int32       `protobuf:"varint,4,opt,name=startType,proto3" json:"startType,omitempty"`
}

func (x *CS2G_StartBattleRoom) Reset() {
	*x = CS2G_StartBattleRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2G_StartBattleRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2G_StartBattleRoom) ProtoMessage() {}

func (x *CS2G_StartBattleRoom) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2G_StartBattleRoom.ProtoReflect.Descriptor instead.
func (*CS2G_StartBattleRoom) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{10}
}

func (x *CS2G_StartBattleRoom) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CS2G_StartBattleRoom) GetIsok() bool {
	if x != nil {
		return x.Isok
	}
	return false
}

func (x *CS2G_StartBattleRoom) GetBaroom() *BattleRoom {
	if x != nil {
		return x.Baroom
	}
	return nil
}

func (x *CS2G_StartBattleRoom) GetStartType() int32 {
	if x != nil {
		return x.StartType
	}
	return 0
}

type CS2G_UpdateBattleRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64      `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Baroom *BattleRoom `protobuf:"bytes,2,opt,name=baroom,proto3" json:"baroom,omitempty"`
}

func (x *CS2G_UpdateBattleRoom) Reset() {
	*x = CS2G_UpdateBattleRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2G_UpdateBattleRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2G_UpdateBattleRoom) ProtoMessage() {}

func (x *CS2G_UpdateBattleRoom) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2G_UpdateBattleRoom.ProtoReflect.Descriptor instead.
func (*CS2G_UpdateBattleRoom) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{11}
}

func (x *CS2G_UpdateBattleRoom) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CS2G_UpdateBattleRoom) GetBaroom() *BattleRoom {
	if x != nil {
		return x.Baroom
	}
	return nil
}

type CS2G_CheckRoleName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId   uint64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoleName string `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
}

func (x *CS2G_CheckRoleName) Reset() {
	*x = CS2G_CheckRoleName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2G_CheckRoleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2G_CheckRoleName) ProtoMessage() {}

func (x *CS2G_CheckRoleName) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2G_CheckRoleName.ProtoReflect.Descriptor instead.
func (*CS2G_CheckRoleName) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{12}
}

func (x *CS2G_CheckRoleName) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CS2G_CheckRoleName) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type G2CS_CheckRoleName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId   uint64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoleName string `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	IsRepeat int32  `protobuf:"varint,3,opt,name=isRepeat,proto3" json:"isRepeat,omitempty"` // 0:改变名字成功 1：名字重复
}

func (x *G2CS_CheckRoleName) Reset() {
	*x = G2CS_CheckRoleName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2CS_CheckRoleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2CS_CheckRoleName) ProtoMessage() {}

func (x *G2CS_CheckRoleName) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2CS_CheckRoleName.ProtoReflect.Descriptor instead.
func (*G2CS_CheckRoleName) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{13}
}

func (x *G2CS_CheckRoleName) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *G2CS_CheckRoleName) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *G2CS_CheckRoleName) GetIsRepeat() int32 {
	if x != nil {
		return x.IsRepeat
	}
	return 0
}

//玩家登录时，以及玩家邮件数据发生改变时，同步邮件数据到客户端
type CS2G_SyncMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID          uint64      `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	MaxSystemMailID uint64      `protobuf:"varint,2,opt,name=maxSystemMailID,proto3" json:"maxSystemMailID,omitempty"`
	MailInfo        []*MailInfo `protobuf:"bytes,3,rep,name=mailInfo,proto3" json:"mailInfo,omitempty"`
}

func (x *CS2G_SyncMail) Reset() {
	*x = CS2G_SyncMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2G_SyncMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2G_SyncMail) ProtoMessage() {}

func (x *CS2G_SyncMail) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2G_SyncMail.ProtoReflect.Descriptor instead.
func (*CS2G_SyncMail) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{14}
}

func (x *CS2G_SyncMail) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *CS2G_SyncMail) GetMaxSystemMailID() uint64 {
	if x != nil {
		return x.MaxSystemMailID
	}
	return 0
}

func (x *CS2G_SyncMail) GetMailInfo() []*MailInfo {
	if x != nil {
		return x.MailInfo
	}
	return nil
}

//玩家操作邮件
type G2CS_OpMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID     uint64               `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	MailOpList []*MailOperationFlag `protobuf:"bytes,2,rep,name=mailOpList,proto3" json:"mailOpList,omitempty"`
}

func (x *G2CS_OpMailRequest) Reset() {
	*x = G2CS_OpMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2CS_OpMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2CS_OpMailRequest) ProtoMessage() {}

func (x *G2CS_OpMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2CS_OpMailRequest.ProtoReflect.Descriptor instead.
func (*G2CS_OpMailRequest) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{15}
}

func (x *G2CS_OpMailRequest) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *G2CS_OpMailRequest) GetMailOpList() []*MailOperationFlag {
	if x != nil {
		return x.MailOpList
	}
	return nil
}

type G2CS_OpMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID         uint64                 `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	MailResultList []*MailOperationResult `protobuf:"bytes,2,rep,name=mailResultList,proto3" json:"mailResultList,omitempty"`
}

func (x *G2CS_OpMailResponse) Reset() {
	*x = G2CS_OpMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2CS_OpMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2CS_OpMailResponse) ProtoMessage() {}

func (x *G2CS_OpMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2CS_OpMailResponse.ProtoReflect.Descriptor instead.
func (*G2CS_OpMailResponse) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{16}
}

func (x *G2CS_OpMailResponse) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *G2CS_OpMailResponse) GetMailResultList() []*MailOperationResult {
	if x != nil {
		return x.MailResultList
	}
	return nil
}

//* 玩家登录消息
type G2CS_RoleLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account       string     `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`    //账号
	RoleId        uint64     `protobuf:"varint,2,opt,name=RoleId,proto3" json:"RoleId,omitempty"`     //默认0
	IsNew         bool       `protobuf:"varint,3,opt,name=IsNew,proto3" json:"IsNew,omitempty"`       //是否新建玩家 默认false
	Serverid      int32      `protobuf:"varint,4,opt,name=Serverid,proto3" json:"Serverid,omitempty"` //服务器ID
	Queueid       int32      `protobuf:"varint,5,opt,name=Queueid,proto3" json:"Queueid,omitempty"`   //排队ID
	Platform      *LoginInfo `protobuf:"bytes,6,opt,name=Platform,proto3" json:"Platform,omitempty"`  // 平台相关的数据信息
	GateSessionId int32      `protobuf:"varint,7,opt,name=gateSessionId,proto3" json:"gateSessionId,omitempty"`
	TimeStamp     int64      `protobuf:"varint,8,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *G2CS_RoleLogin) Reset() {
	*x = G2CS_RoleLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2CS_RoleLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2CS_RoleLogin) ProtoMessage() {}

func (x *G2CS_RoleLogin) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2CS_RoleLogin.ProtoReflect.Descriptor instead.
func (*G2CS_RoleLogin) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{17}
}

func (x *G2CS_RoleLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *G2CS_RoleLogin) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *G2CS_RoleLogin) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *G2CS_RoleLogin) GetServerid() int32 {
	if x != nil {
		return x.Serverid
	}
	return 0
}

func (x *G2CS_RoleLogin) GetQueueid() int32 {
	if x != nil {
		return x.Queueid
	}
	return 0
}

func (x *G2CS_RoleLogin) GetPlatform() *LoginInfo {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *G2CS_RoleLogin) GetGateSessionId() int32 {
	if x != nil {
		return x.GateSessionId
	}
	return 0
}

func (x *G2CS_RoleLogin) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

//* 玩家登录消息
type CS2G_RoleLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account       string     `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`    //账号
	RoleId        uint64     `protobuf:"varint,2,opt,name=RoleId,proto3" json:"RoleId,omitempty"`     //默认0
	IsNew         bool       `protobuf:"varint,3,opt,name=IsNew,proto3" json:"IsNew,omitempty"`       //是否新建玩家 默认false
	Serverid      int32      `protobuf:"varint,4,opt,name=Serverid,proto3" json:"Serverid,omitempty"` //服务器ID
	Queueid       int32      `protobuf:"varint,5,opt,name=Queueid,proto3" json:"Queueid,omitempty"`   //排队ID
	Platform      *LoginInfo `protobuf:"bytes,6,opt,name=Platform,proto3" json:"Platform,omitempty"`  // 平台相关的数据信息
	GateSessionId int32      `protobuf:"varint,7,opt,name=gateSessionId,proto3" json:"gateSessionId,omitempty"`
	TimeStamp     int64      `protobuf:"varint,8,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *CS2G_RoleLogin) Reset() {
	*x = CS2G_RoleLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2G_RoleLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2G_RoleLogin) ProtoMessage() {}

func (x *CS2G_RoleLogin) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2G_RoleLogin.ProtoReflect.Descriptor instead.
func (*CS2G_RoleLogin) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{18}
}

func (x *CS2G_RoleLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CS2G_RoleLogin) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CS2G_RoleLogin) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *CS2G_RoleLogin) GetServerid() int32 {
	if x != nil {
		return x.Serverid
	}
	return 0
}

func (x *CS2G_RoleLogin) GetQueueid() int32 {
	if x != nil {
		return x.Queueid
	}
	return 0
}

func (x *CS2G_RoleLogin) GetPlatform() *LoginInfo {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *CS2G_RoleLogin) GetGateSessionId() int32 {
	if x != nil {
		return x.GateSessionId
	}
	return 0
}

func (x *CS2G_RoleLogin) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

//被踢下线
type G2CS_KickRoleOffLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64          `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"` //下线角色id
	Data   *G2CS_RoleLogin `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *G2CS_KickRoleOffLine) Reset() {
	*x = G2CS_KickRoleOffLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2CS_KickRoleOffLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2CS_KickRoleOffLine) ProtoMessage() {}

func (x *G2CS_KickRoleOffLine) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2CS_KickRoleOffLine.ProtoReflect.Descriptor instead.
func (*G2CS_KickRoleOffLine) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{19}
}

func (x *G2CS_KickRoleOffLine) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *G2CS_KickRoleOffLine) GetData() *G2CS_RoleLogin {
	if x != nil {
		return x.Data
	}
	return nil
}

//被踢下线
type CS2G_KickRoleOffLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64          `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"` //下线角色id
	Data   *G2CS_RoleLogin `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CS2G_KickRoleOffLine) Reset() {
	*x = CS2G_KickRoleOffLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GS_Message_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2G_KickRoleOffLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2G_KickRoleOffLine) ProtoMessage() {}

func (x *CS2G_KickRoleOffLine) ProtoReflect() protoreflect.Message {
	mi := &file_B_GS_Message_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2G_KickRoleOffLine.ProtoReflect.Descriptor instead.
func (*CS2G_KickRoleOffLine) Descriptor() ([]byte, []int) {
	return file_B_GS_Message_proto_rawDescGZIP(), []int{20}
}

func (x *CS2G_KickRoleOffLine) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CS2G_KickRoleOffLine) GetData() *G2CS_RoleLogin {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_B_GS_Message_proto protoreflect.FileDescriptor

var file_B_GS_Message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x42, 0x5f, 0x47, 0x53, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x42, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x42, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0f,
	0x47, 0x53, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4e, 0x74, 0x66, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x0f,
	0x47, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x24, 0x0a,
	0x0d, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0xbd, 0x01, 0x0a, 0x10, 0x47, 0x53,
	0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x24, 0x0a,
	0x0d, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x0d, 0x47, 0x53, 0x5f,
	0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x4e, 0x74, 0x66, 0x12, 0x4c, 0x0a, 0x0f, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x44, 0x0a, 0x12, 0x47, 0x32, 0x43, 0x53,
	0x5f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x22, 0x5b,
	0x0a, 0x12, 0x43, 0x53, 0x32, 0x47, 0x5f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x03,
	0x72, 0x72, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x03, 0x72, 0x72, 0x64, 0x22, 0xf8, 0x01, 0x0a, 0x13,
	0x47, 0x32, 0x43, 0x53, 0x5f, 0x4f, 0x70, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x08, 0x52,
	0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x52, 0x6f,
	0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x76, 0x0a, 0x13, 0x43, 0x53, 0x32, 0x47, 0x5f, 0x4f,
	0x70, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x6f, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x6f, 0x6b, 0x12, 0x33, 0x0a, 0x06, 0x62, 0x61, 0x72,
	0x6f, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x06, 0x62, 0x61, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x62,
	0x0a, 0x12, 0x47, 0x32, 0x43, 0x53, 0x5f, 0x4f, 0x75, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x22, 0x64, 0x0a, 0x14, 0x47, 0x32, 0x43, 0x53, 0x5f, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x14, 0x43, 0x53, 0x32,
	0x47, 0x5f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x6f,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x6f, 0x6b, 0x12, 0x33, 0x0a,
	0x06, 0x62, 0x61, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x06, 0x62, 0x61, 0x72, 0x6f,
	0x6f, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x64, 0x0a, 0x15, 0x43, 0x53, 0x32, 0x47, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x33, 0x0a, 0x06, 0x62, 0x61, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x06,
	0x62, 0x61, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x48, 0x0a, 0x12, 0x43, 0x53, 0x32, 0x47, 0x5f, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x64, 0x0a, 0x12, 0x47, 0x32, 0x43, 0x53, 0x5f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x73,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x0d, 0x43, 0x53, 0x32, 0x47, 0x5f,
	0x53, 0x79, 0x6e, 0x63, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69,
	0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x6d, 0x61, 0x78, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x61,
	0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d,
	0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x70, 0x0a, 0x12, 0x47, 0x32, 0x43, 0x53, 0x5f, 0x4f, 0x70, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12,
	0x42, 0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x0a, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x70, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x7b, 0x0a, 0x13, 0x47, 0x32, 0x43, 0x53, 0x5f, 0x4f, 0x70, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65,
	0x49, 0x44, 0x12, 0x4c, 0x0a, 0x0e, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x61, 0x69,
	0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x0e, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x8a, 0x02, 0x0a, 0x0e, 0x47, 0x32, 0x43, 0x53, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x51, 0x75, 0x65, 0x75, 0x65, 0x69,
	0x64, 0x12, 0x36, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x8a, 0x02,
	0x0a, 0x0e, 0x43, 0x53, 0x32, 0x47, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x49, 0x73, 0x4e, 0x65, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x75, 0x65, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x51, 0x75, 0x65, 0x75, 0x65, 0x69, 0x64, 0x12, 0x36,
	0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x24, 0x0a, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x67,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x63, 0x0a, 0x14, 0x47, 0x32,
	0x43, 0x53, 0x5f, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x66, 0x66, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x32, 0x43, 0x53, 0x5f,
	0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x63, 0x0a, 0x14, 0x43, 0x53, 0x32, 0x47, 0x5f, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x6f, 0x6c, 0x65,
	0x4f, 0x66, 0x66, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x47, 0x32, 0x43, 0x53, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_B_GS_Message_proto_rawDescOnce sync.Once
	file_B_GS_Message_proto_rawDescData = file_B_GS_Message_proto_rawDesc
)

func file_B_GS_Message_proto_rawDescGZIP() []byte {
	file_B_GS_Message_proto_rawDescOnce.Do(func() {
		file_B_GS_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_B_GS_Message_proto_rawDescData)
	})
	return file_B_GS_Message_proto_rawDescData
}

var file_B_GS_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_B_GS_Message_proto_goTypes = []interface{}{
	(*GS_ConnectedNtf)(nil),       // 0: network.message.GS_ConnectedNtf
	(*GS_LoginRequest)(nil),       // 1: network.message.GS_LoginRequest
	(*GS_LoginResponse)(nil),      // 2: network.message.GS_LoginResponse
	(*GS_KickOutNtf)(nil),         // 3: network.message.GS_KickOutNtf
	(*G2CS_GetBattleRoom)(nil),    // 4: network.message.G2CS_GetBattleRoom
	(*CS2G_GetBattleRoom)(nil),    // 5: network.message.CS2G_GetBattleRoom
	(*G2CS_OpenBattleRoom)(nil),   // 6: network.message.G2CS_OpenBattleRoom
	(*CS2G_OpenBattleRoom)(nil),   // 7: network.message.CS2G_OpenBattleRoom
	(*G2CS_OutBattleRoom)(nil),    // 8: network.message.G2CS_OutBattleRoom
	(*G2CS_StartBattleRoom)(nil),  // 9: network.message.G2CS_StartBattleRoom
	(*CS2G_StartBattleRoom)(nil),  // 10: network.message.CS2G_StartBattleRoom
	(*CS2G_UpdateBattleRoom)(nil), // 11: network.message.CS2G_UpdateBattleRoom
	(*CS2G_CheckRoleName)(nil),    // 12: network.message.CS2G_CheckRoleName
	(*G2CS_CheckRoleName)(nil),    // 13: network.message.G2CS_CheckRoleName
	(*CS2G_SyncMail)(nil),         // 14: network.message.CS2G_SyncMail
	(*G2CS_OpMailRequest)(nil),    // 15: network.message.G2CS_OpMailRequest
	(*G2CS_OpMailResponse)(nil),   // 16: network.message.G2CS_OpMailResponse
	(*G2CS_RoleLogin)(nil),        // 17: network.message.G2CS_RoleLogin
	(*CS2G_RoleLogin)(nil),        // 18: network.message.CS2G_RoleLogin
	(*G2CS_KickRoleOffLine)(nil),  // 19: network.message.G2CS_KickRoleOffLine
	(*CS2G_KickRoleOffLine)(nil),  // 20: network.message.CS2G_KickRoleOffLine
	(Result)(0),                   // 21: network.message.Result
	(*B_UserSessionInfo)(nil),     // 22: network.message.B_UserSessionInfo
	(*BattleRoom)(nil),            // 23: network.message.BattleRoom
	(*RoomRoleData)(nil),          // 24: network.message.RoomRoleData
	(*MailInfo)(nil),              // 25: network.message.MailInfo
	(*MailOperationFlag)(nil),     // 26: network.message.MailOperationFlag
	(*MailOperationResult)(nil),   // 27: network.message.MailOperationResult
	(*LoginInfo)(nil),             // 28: network.message.LoginInfo
}
var file_B_GS_Message_proto_depIdxs = []int32{
	21, // 0: network.message.GS_LoginResponse.result:type_name -> network.message.Result
	22, // 1: network.message.GS_KickOutNtf.userSessionInfo:type_name -> network.message.B_UserSessionInfo
	23, // 2: network.message.CS2G_GetBattleRoom.rrd:type_name -> network.message.BattleRoom
	24, // 3: network.message.G2CS_OpenBattleRoom.RoleData:type_name -> network.message.RoomRoleData
	23, // 4: network.message.CS2G_OpenBattleRoom.baroom:type_name -> network.message.BattleRoom
	23, // 5: network.message.CS2G_StartBattleRoom.baroom:type_name -> network.message.BattleRoom
	23, // 6: network.message.CS2G_UpdateBattleRoom.baroom:type_name -> network.message.BattleRoom
	25, // 7: network.message.CS2G_SyncMail.mailInfo:type_name -> network.message.MailInfo
	26, // 8: network.message.G2CS_OpMailRequest.mailOpList:type_name -> network.message.MailOperationFlag
	27, // 9: network.message.G2CS_OpMailResponse.mailResultList:type_name -> network.message.MailOperationResult
	28, // 10: network.message.G2CS_RoleLogin.Platform:type_name -> network.message.LoginInfo
	28, // 11: network.message.CS2G_RoleLogin.Platform:type_name -> network.message.LoginInfo
	17, // 12: network.message.G2CS_KickRoleOffLine.data:type_name -> network.message.G2CS_RoleLogin
	17, // 13: network.message.CS2G_KickRoleOffLine.data:type_name -> network.message.G2CS_RoleLogin
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_B_GS_Message_proto_init() }
func file_B_GS_Message_proto_init() {
	if File_B_GS_Message_proto != nil {
		return
	}
	file_B_Communication_proto_init()
	file_BaseInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_B_GS_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GS_ConnectedNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GS_LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GS_LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GS_KickOutNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2CS_GetBattleRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2G_GetBattleRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2CS_OpenBattleRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2G_OpenBattleRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2CS_OutBattleRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2CS_StartBattleRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2G_StartBattleRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2G_UpdateBattleRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2G_CheckRoleName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2CS_CheckRoleName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2G_SyncMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2CS_OpMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2CS_OpMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2CS_RoleLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2G_RoleLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2CS_KickRoleOffLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GS_Message_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2G_KickRoleOffLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_B_GS_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_B_GS_Message_proto_goTypes,
		DependencyIndexes: file_B_GS_Message_proto_depIdxs,
		MessageInfos:      file_B_GS_Message_proto_msgTypes,
	}.Build()
	File_B_GS_Message_proto = out.File
	file_B_GS_Message_proto_rawDesc = nil
	file_B_GS_Message_proto_goTypes = nil
	file_B_GS_Message_proto_depIdxs = nil
}
