// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.9.0
// source: B_GT_Message.proto

package network_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//* GT与GS 登录请求
type GT_LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account       string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Gold          int32  `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	UserSessionId int32  `protobuf:"varint,3,opt,name=userSessionId,proto3" json:"userSessionId,omitempty"`
}

func (x *GT_LoginRequest) Reset() {
	*x = GT_LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GT_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GT_LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GT_LoginRequest) ProtoMessage() {}

func (x *GT_LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_GT_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GT_LoginRequest.ProtoReflect.Descriptor instead.
func (*GT_LoginRequest) Descriptor() ([]byte, []int) {
	return file_B_GT_Message_proto_rawDescGZIP(), []int{0}
}

func (x *GT_LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GT_LoginRequest) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GT_LoginRequest) GetUserSessionId() int32 {
	if x != nil {
		return x.UserSessionId
	}
	return 0
}

type GT_LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result        Result `protobuf:"varint,1,opt,name=result,proto3,enum=network.message.Result" json:"result,omitempty"`
	Account       string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Gold          int32  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	UserSessionId int32  `protobuf:"varint,4,opt,name=userSessionId,proto3" json:"userSessionId,omitempty"`
}

func (x *GT_LoginResponse) Reset() {
	*x = GT_LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GT_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GT_LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GT_LoginResponse) ProtoMessage() {}

func (x *GT_LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_GT_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GT_LoginResponse.ProtoReflect.Descriptor instead.
func (*GT_LoginResponse) Descriptor() ([]byte, []int) {
	return file_B_GT_Message_proto_rawDescGZIP(), []int{1}
}

func (x *GT_LoginResponse) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_SUCCESS
}

func (x *GT_LoginResponse) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GT_LoginResponse) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GT_LoginResponse) GetUserSessionId() int32 {
	if x != nil {
		return x.UserSessionId
	}
	return 0
}

//* GT GATE登出通知
type GT_LogoutNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionInfo *B_UserSessionInfo `protobuf:"bytes,1,opt,name=userSessionInfo,proto3" json:"userSessionInfo,omitempty"`
}

func (x *GT_LogoutNtf) Reset() {
	*x = GT_LogoutNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GT_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GT_LogoutNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GT_LogoutNtf) ProtoMessage() {}

func (x *GT_LogoutNtf) ProtoReflect() protoreflect.Message {
	mi := &file_B_GT_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GT_LogoutNtf.ProtoReflect.Descriptor instead.
func (*GT_LogoutNtf) Descriptor() ([]byte, []int) {
	return file_B_GT_Message_proto_rawDescGZIP(), []int{2}
}

func (x *GT_LogoutNtf) GetUserSessionInfo() *B_UserSessionInfo {
	if x != nil {
		return x.UserSessionInfo
	}
	return nil
}

//* GT 连接请求
type GT_ConnectedNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateServerId int32 `protobuf:"varint,1,opt,name=gateServerId,proto3" json:"gateServerId,omitempty"`
}

func (x *GT_ConnectedNtf) Reset() {
	*x = GT_ConnectedNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GT_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GT_ConnectedNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GT_ConnectedNtf) ProtoMessage() {}

func (x *GT_ConnectedNtf) ProtoReflect() protoreflect.Message {
	mi := &file_B_GT_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GT_ConnectedNtf.ProtoReflect.Descriptor instead.
func (*GT_ConnectedNtf) Descriptor() ([]byte, []int) {
	return file_B_GT_Message_proto_rawDescGZIP(), []int{3}
}

func (x *GT_ConnectedNtf) GetGateServerId() int32 {
	if x != nil {
		return x.GateServerId
	}
	return 0
}

//* GT to battle test 请求
type GT_TestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateServerId  int32 `protobuf:"varint,1,opt,name=gateServerId,proto3" json:"gateServerId,omitempty"`
	UserSessionId int32 `protobuf:"varint,2,opt,name=userSessionId,proto3" json:"userSessionId,omitempty"`
}

func (x *GT_TestRequest) Reset() {
	*x = GT_TestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GT_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GT_TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GT_TestRequest) ProtoMessage() {}

func (x *GT_TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_GT_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GT_TestRequest.ProtoReflect.Descriptor instead.
func (*GT_TestRequest) Descriptor() ([]byte, []int) {
	return file_B_GT_Message_proto_rawDescGZIP(), []int{4}
}

func (x *GT_TestRequest) GetGateServerId() int32 {
	if x != nil {
		return x.GateServerId
	}
	return 0
}

func (x *GT_TestRequest) GetUserSessionId() int32 {
	if x != nil {
		return x.UserSessionId
	}
	return 0
}

//* GT 连接GateManager请求
type GT_ConnectedGateManagerNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateServerId         int32  `protobuf:"varint,1,opt,name=gateServerId,proto3" json:"gateServerId,omitempty"`
	ClientConnectAddress string `protobuf:"bytes,2,opt,name=clientConnectAddress,proto3" json:"clientConnectAddress,omitempty"`
}

func (x *GT_ConnectedGateManagerNtf) Reset() {
	*x = GT_ConnectedGateManagerNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GT_Message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GT_ConnectedGateManagerNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GT_ConnectedGateManagerNtf) ProtoMessage() {}

func (x *GT_ConnectedGateManagerNtf) ProtoReflect() protoreflect.Message {
	mi := &file_B_GT_Message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GT_ConnectedGateManagerNtf.ProtoReflect.Descriptor instead.
func (*GT_ConnectedGateManagerNtf) Descriptor() ([]byte, []int) {
	return file_B_GT_Message_proto_rawDescGZIP(), []int{5}
}

func (x *GT_ConnectedGateManagerNtf) GetGateServerId() int32 {
	if x != nil {
		return x.GateServerId
	}
	return 0
}

func (x *GT_ConnectedGateManagerNtf) GetClientConnectAddress() string {
	if x != nil {
		return x.ClientConnectAddress
	}
	return ""
}

//* GT to battle test 响应
type GT_TestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSessionId int32 `protobuf:"varint,1,opt,name=userSessionId,proto3" json:"userSessionId,omitempty"`
	RandomNum     int32 `protobuf:"varint,2,opt,name=randomNum,proto3" json:"randomNum,omitempty"`
}

func (x *GT_TestResponse) Reset() {
	*x = GT_TestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_GT_Message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GT_TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GT_TestResponse) ProtoMessage() {}

func (x *GT_TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_GT_Message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GT_TestResponse.ProtoReflect.Descriptor instead.
func (*GT_TestResponse) Descriptor() ([]byte, []int) {
	return file_B_GT_Message_proto_rawDescGZIP(), []int{6}
}

func (x *GT_TestResponse) GetUserSessionId() int32 {
	if x != nil {
		return x.UserSessionId
	}
	return 0
}

func (x *GT_TestResponse) GetRandomNum() int32 {
	if x != nil {
		return x.RandomNum
	}
	return 0
}

var File_B_GT_Message_proto protoreflect.FileDescriptor

var file_B_GT_Message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x42, 0x5f, 0x47, 0x54, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x42, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x42, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x0f,
	0x47, 0x54, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x24, 0x0a,
	0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x97, 0x01, 0x0a, 0x10, 0x47, 0x54, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x5c, 0x0a,
	0x0c, 0x47, 0x54, 0x5f, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x4e, 0x74, 0x66, 0x12, 0x4c, 0x0a,
	0x0f, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x75, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x35, 0x0a, 0x0f, 0x47,
	0x54, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4e, 0x74, 0x66, 0x12, 0x22,
	0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x5a, 0x0a, 0x0e, 0x47, 0x54, 0x5f, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x67, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x74,
	0x0a, 0x1a, 0x47, 0x54, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x47, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x4e, 0x74, 0x66, 0x12, 0x22, 0x0a, 0x0c,
	0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x32, 0x0a, 0x14, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x55, 0x0a, 0x0f, 0x47, 0x54, 0x5f, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x42, 0x13, 0x5a, 0x11, 0x2e,
	0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_B_GT_Message_proto_rawDescOnce sync.Once
	file_B_GT_Message_proto_rawDescData = file_B_GT_Message_proto_rawDesc
)

func file_B_GT_Message_proto_rawDescGZIP() []byte {
	file_B_GT_Message_proto_rawDescOnce.Do(func() {
		file_B_GT_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_B_GT_Message_proto_rawDescData)
	})
	return file_B_GT_Message_proto_rawDescData
}

var file_B_GT_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_B_GT_Message_proto_goTypes = []interface{}{
	(*GT_LoginRequest)(nil),            // 0: network.message.GT_LoginRequest
	(*GT_LoginResponse)(nil),           // 1: network.message.GT_LoginResponse
	(*GT_LogoutNtf)(nil),               // 2: network.message.GT_LogoutNtf
	(*GT_ConnectedNtf)(nil),            // 3: network.message.GT_ConnectedNtf
	(*GT_TestRequest)(nil),             // 4: network.message.GT_TestRequest
	(*GT_ConnectedGateManagerNtf)(nil), // 5: network.message.GT_ConnectedGateManagerNtf
	(*GT_TestResponse)(nil),            // 6: network.message.GT_TestResponse
	(Result)(0),                        // 7: network.message.Result
	(*B_UserSessionInfo)(nil),          // 8: network.message.B_UserSessionInfo
}
var file_B_GT_Message_proto_depIdxs = []int32{
	7, // 0: network.message.GT_LoginResponse.result:type_name -> network.message.Result
	8, // 1: network.message.GT_LogoutNtf.userSessionInfo:type_name -> network.message.B_UserSessionInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_B_GT_Message_proto_init() }
func file_B_GT_Message_proto_init() {
	if File_B_GT_Message_proto != nil {
		return
	}
	file_B_Communication_proto_init()
	file_BaseInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_B_GT_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GT_LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GT_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GT_LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GT_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GT_LogoutNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GT_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GT_ConnectedNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GT_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GT_TestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GT_Message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GT_ConnectedGateManagerNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_GT_Message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GT_TestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_B_GT_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_B_GT_Message_proto_goTypes,
		DependencyIndexes: file_B_GT_Message_proto_depIdxs,
		MessageInfos:      file_B_GT_Message_proto_msgTypes,
	}.Build()
	File_B_GT_Message_proto = out.File
	file_B_GT_Message_proto_rawDesc = nil
	file_B_GT_Message_proto_goTypes = nil
	file_B_GT_Message_proto_depIdxs = nil
}
