// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.9.0
// source: B_MS_Message.proto

package network_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//* GS与GT 连接请求
type MS_ConnectedNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId int32 `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *MS_ConnectedNtf) Reset() {
	*x = MS_ConnectedNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MS_ConnectedNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MS_ConnectedNtf) ProtoMessage() {}

func (x *MS_ConnectedNtf) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MS_ConnectedNtf.ProtoReflect.Descriptor instead.
func (*MS_ConnectedNtf) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{0}
}

func (x *MS_ConnectedNtf) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type CS2MS_SendRoleMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID      int64    `protobuf:"varint,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	GmSender       string   `protobuf:"bytes,2,opt,name=gmSender,proto3" json:"gmSender,omitempty"`                     //操作 发送GM后台的人 的真实ID
	GmEditor       string   `protobuf:"bytes,3,opt,name=gmEditor,proto3" json:"gmEditor,omitempty"`                     //审核 GM邮箱申请 并同意的人 的真实ID
	SendName       string   `protobuf:"bytes,4,opt,name=sendName,proto3" json:"sendName,omitempty"`                     //邮件内容:发件人的名字
	IsSendAll      bool     `protobuf:"varint,5,opt,name=isSendAll,proto3" json:"isSendAll,omitempty"`                  //是否是一封全体邮件
	SexType        int32    `protobuf:"varint,6,opt,name=sexType,proto3" json:"sexType,omitempty"`                      //如果是全体邮件 那么性别是 0全体 1男  2女
	LvStart        int32    `protobuf:"varint,7,opt,name=lvStart,proto3" json:"lvStart,omitempty"`                      //如果是全体邮件 那么等级范围 如果没有等级范围那么值为0
	LvEnd          int32    `protobuf:"varint,8,opt,name=lvEnd,proto3" json:"lvEnd,omitempty"`                          //如果是全体邮件 那么等级范围 如果没有等级范围那么值为0
	SuccessPlayers []uint64 `protobuf:"varint,9,rep,packed,name=successPlayers,proto3" json:"successPlayers,omitempty"` //center检测后 真实存在的玩家
	FailPlayers    []uint64 `protobuf:"varint,11,rep,packed,name=failPlayers,proto3" json:"failPlayers,omitempty"`      //center检测侯 不存在的玩家
	Title          string   `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`                          //邮件标题
	ContentStr     string   `protobuf:"bytes,13,opt,name=contentStr,proto3" json:"contentStr,omitempty"`                //邮件内容
	ItemList       []*Items `protobuf:"bytes,14,rep,name=itemList,proto3" json:"itemList,omitempty"`                    //邮件附件物品
	TimeType       int32    `protobuf:"varint,15,opt,name=timeType,proto3" json:"timeType,omitempty"`                   //时间类型 0为立即发送 1为在范围时间内玩家登录游戏后自动推送邮件 2在范围时间内的创角玩家才能获得奖励
	StartTime      int64    `protobuf:"varint,16,opt,name=startTime,proto3" json:"startTime,omitempty"`                 //开始时间 单位格林威治毫秒 时间类型 0时不需要处理
	EndTime        int64    `protobuf:"varint,17,opt,name=endTime,proto3" json:"endTime,omitempty"`                     //结束时间 单位格林威治毫秒  时间类型 0时不需要处理
	SendTime       int64    `protobuf:"varint,18,opt,name=sendTime,proto3" json:"sendTime,omitempty"`                   //GM工具发送 这封邮件的时间 一般是审核通过的时间
}

func (x *CS2MS_SendRoleMailRequest) Reset() {
	*x = CS2MS_SendRoleMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_SendRoleMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_SendRoleMailRequest) ProtoMessage() {}

func (x *CS2MS_SendRoleMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_SendRoleMailRequest.ProtoReflect.Descriptor instead.
func (*CS2MS_SendRoleMailRequest) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{1}
}

func (x *CS2MS_SendRoleMailRequest) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *CS2MS_SendRoleMailRequest) GetGmSender() string {
	if x != nil {
		return x.GmSender
	}
	return ""
}

func (x *CS2MS_SendRoleMailRequest) GetGmEditor() string {
	if x != nil {
		return x.GmEditor
	}
	return ""
}

func (x *CS2MS_SendRoleMailRequest) GetSendName() string {
	if x != nil {
		return x.SendName
	}
	return ""
}

func (x *CS2MS_SendRoleMailRequest) GetIsSendAll() bool {
	if x != nil {
		return x.IsSendAll
	}
	return false
}

func (x *CS2MS_SendRoleMailRequest) GetSexType() int32 {
	if x != nil {
		return x.SexType
	}
	return 0
}

func (x *CS2MS_SendRoleMailRequest) GetLvStart() int32 {
	if x != nil {
		return x.LvStart
	}
	return 0
}

func (x *CS2MS_SendRoleMailRequest) GetLvEnd() int32 {
	if x != nil {
		return x.LvEnd
	}
	return 0
}

func (x *CS2MS_SendRoleMailRequest) GetSuccessPlayers() []uint64 {
	if x != nil {
		return x.SuccessPlayers
	}
	return nil
}

func (x *CS2MS_SendRoleMailRequest) GetFailPlayers() []uint64 {
	if x != nil {
		return x.FailPlayers
	}
	return nil
}

func (x *CS2MS_SendRoleMailRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CS2MS_SendRoleMailRequest) GetContentStr() string {
	if x != nil {
		return x.ContentStr
	}
	return ""
}

func (x *CS2MS_SendRoleMailRequest) GetItemList() []*Items {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *CS2MS_SendRoleMailRequest) GetTimeType() int32 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *CS2MS_SendRoleMailRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CS2MS_SendRoleMailRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CS2MS_SendRoleMailRequest) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type CS2MS_SendRoleMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID      int64    `protobuf:"varint,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	ErrorCode      Result   `protobuf:"varint,2,opt,name=errorCode,proto3,enum=network.message.Result" json:"errorCode,omitempty"` //错误码 0成功 非0失败
	SuccessPlayers []uint64 `protobuf:"varint,3,rep,packed,name=successPlayers,proto3" json:"successPlayers,omitempty"`            //center检测后 真实存在的玩家,发送成功的玩家id
	FailPlayers    []uint64 `protobuf:"varint,4,rep,packed,name=failPlayers,proto3" json:"failPlayers,omitempty"`                  //center检测侯 不存在的玩家，发送失败的玩家id
}

func (x *CS2MS_SendRoleMailResponse) Reset() {
	*x = CS2MS_SendRoleMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_SendRoleMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_SendRoleMailResponse) ProtoMessage() {}

func (x *CS2MS_SendRoleMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_SendRoleMailResponse.ProtoReflect.Descriptor instead.
func (*CS2MS_SendRoleMailResponse) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{2}
}

func (x *CS2MS_SendRoleMailResponse) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *CS2MS_SendRoleMailResponse) GetErrorCode() Result {
	if x != nil {
		return x.ErrorCode
	}
	return Result_SUCCESS
}

func (x *CS2MS_SendRoleMailResponse) GetSuccessPlayers() []uint64 {
	if x != nil {
		return x.SuccessPlayers
	}
	return nil
}

func (x *CS2MS_SendRoleMailResponse) GetFailPlayers() []uint64 {
	if x != nil {
		return x.FailPlayers
	}
	return nil
}

type CS2MS_GetAllMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID int64  `protobuf:"varint,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	RoleID    uint64 `protobuf:"varint,2,opt,name=roleID,proto3" json:"roleID,omitempty"` //查询这个roleid的邮件列表
}

func (x *CS2MS_GetAllMailRequest) Reset() {
	*x = CS2MS_GetAllMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_GetAllMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_GetAllMailRequest) ProtoMessage() {}

func (x *CS2MS_GetAllMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_GetAllMailRequest.ProtoReflect.Descriptor instead.
func (*CS2MS_GetAllMailRequest) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{3}
}

func (x *CS2MS_GetAllMailRequest) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *CS2MS_GetAllMailRequest) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

type CS2MS_GetAllMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID int64       `protobuf:"varint,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	ErrorCode Result      `protobuf:"varint,2,opt,name=errorCode,proto3,enum=network.message.Result" json:"errorCode,omitempty"` //错误码 0成功 非0失败
	MailInfo  []*MailInfo `protobuf:"bytes,3,rep,name=mailInfo,proto3" json:"mailInfo,omitempty"`                                //邮件列表
}

func (x *CS2MS_GetAllMailResponse) Reset() {
	*x = CS2MS_GetAllMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_GetAllMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_GetAllMailResponse) ProtoMessage() {}

func (x *CS2MS_GetAllMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_GetAllMailResponse.ProtoReflect.Descriptor instead.
func (*CS2MS_GetAllMailResponse) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{4}
}

func (x *CS2MS_GetAllMailResponse) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *CS2MS_GetAllMailResponse) GetErrorCode() Result {
	if x != nil {
		return x.ErrorCode
	}
	return Result_SUCCESS
}

func (x *CS2MS_GetAllMailResponse) GetMailInfo() []*MailInfo {
	if x != nil {
		return x.MailInfo
	}
	return nil
}

type CS2MS_DelMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID int64  `protobuf:"varint,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	RoleID    uint64 `protobuf:"varint,2,opt,name=roleID,proto3" json:"roleID,omitempty"` //删除这个roleid的邮件
	MailID    uint64 `protobuf:"varint,3,opt,name=mailID,proto3" json:"mailID,omitempty"` //邮件的ID
}

func (x *CS2MS_DelMailRequest) Reset() {
	*x = CS2MS_DelMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_DelMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_DelMailRequest) ProtoMessage() {}

func (x *CS2MS_DelMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_DelMailRequest.ProtoReflect.Descriptor instead.
func (*CS2MS_DelMailRequest) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{5}
}

func (x *CS2MS_DelMailRequest) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *CS2MS_DelMailRequest) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *CS2MS_DelMailRequest) GetMailID() uint64 {
	if x != nil {
		return x.MailID
	}
	return 0
}

type CS2MS_DelMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID int64  `protobuf:"varint,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	ErrorCode Result `protobuf:"varint,2,opt,name=errorCode,proto3,enum=network.message.Result" json:"errorCode,omitempty"` //错误码 0成功 非0失败
}

func (x *CS2MS_DelMailResponse) Reset() {
	*x = CS2MS_DelMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_DelMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_DelMailResponse) ProtoMessage() {}

func (x *CS2MS_DelMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_DelMailResponse.ProtoReflect.Descriptor instead.
func (*CS2MS_DelMailResponse) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{6}
}

func (x *CS2MS_DelMailResponse) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *CS2MS_DelMailResponse) GetErrorCode() Result {
	if x != nil {
		return x.ErrorCode
	}
	return Result_SUCCESS
}

//玩家登录时，以及玩家邮件数据发生改变时，同步邮件数据到客户端
type CS2MS_SyncMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID          uint64 `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	MaxSystemMailID uint64 `protobuf:"varint,2,opt,name=maxSystemMailID,proto3" json:"maxSystemMailID,omitempty"`
}

func (x *CS2MS_SyncMailRequest) Reset() {
	*x = CS2MS_SyncMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_SyncMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_SyncMailRequest) ProtoMessage() {}

func (x *CS2MS_SyncMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_SyncMailRequest.ProtoReflect.Descriptor instead.
func (*CS2MS_SyncMailRequest) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{7}
}

func (x *CS2MS_SyncMailRequest) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *CS2MS_SyncMailRequest) GetMaxSystemMailID() uint64 {
	if x != nil {
		return x.MaxSystemMailID
	}
	return 0
}

//玩家登录时，以及玩家邮件数据发生改变时，同步邮件数据到客户端
type CS2MS_SyncMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID          uint64      `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	MaxSystemMailID uint64      `protobuf:"varint,2,opt,name=maxSystemMailID,proto3" json:"maxSystemMailID,omitempty"`
	MailInfo        []*MailInfo `protobuf:"bytes,3,rep,name=mailInfo,proto3" json:"mailInfo,omitempty"`
}

func (x *CS2MS_SyncMailResponse) Reset() {
	*x = CS2MS_SyncMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_SyncMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_SyncMailResponse) ProtoMessage() {}

func (x *CS2MS_SyncMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_SyncMailResponse.ProtoReflect.Descriptor instead.
func (*CS2MS_SyncMailResponse) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{8}
}

func (x *CS2MS_SyncMailResponse) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *CS2MS_SyncMailResponse) GetMaxSystemMailID() uint64 {
	if x != nil {
		return x.MaxSystemMailID
	}
	return 0
}

func (x *CS2MS_SyncMailResponse) GetMailInfo() []*MailInfo {
	if x != nil {
		return x.MailInfo
	}
	return nil
}

//玩家操作邮件
type CS2MS_OpMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID     uint64               `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	MailOpList []*MailOperationFlag `protobuf:"bytes,2,rep,name=mailOpList,proto3" json:"mailOpList,omitempty"`
}

func (x *CS2MS_OpMailRequest) Reset() {
	*x = CS2MS_OpMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_OpMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_OpMailRequest) ProtoMessage() {}

func (x *CS2MS_OpMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_OpMailRequest.ProtoReflect.Descriptor instead.
func (*CS2MS_OpMailRequest) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{9}
}

func (x *CS2MS_OpMailRequest) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *CS2MS_OpMailRequest) GetMailOpList() []*MailOperationFlag {
	if x != nil {
		return x.MailOpList
	}
	return nil
}

type CS2MS_OpMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID         uint64                 `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	MailResultList []*MailOperationResult `protobuf:"bytes,2,rep,name=mailResultList,proto3" json:"mailResultList,omitempty"`
}

func (x *CS2MS_OpMailResponse) Reset() {
	*x = CS2MS_OpMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_B_MS_Message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CS2MS_OpMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS2MS_OpMailResponse) ProtoMessage() {}

func (x *CS2MS_OpMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_B_MS_Message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS2MS_OpMailResponse.ProtoReflect.Descriptor instead.
func (*CS2MS_OpMailResponse) Descriptor() ([]byte, []int) {
	return file_B_MS_Message_proto_rawDescGZIP(), []int{10}
}

func (x *CS2MS_OpMailResponse) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *CS2MS_OpMailResponse) GetMailResultList() []*MailOperationResult {
	if x != nil {
		return x.MailResultList
	}
	return nil
}

var File_B_MS_Message_proto protoreflect.FileDescriptor

var file_B_MS_Message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x42, 0x5f, 0x4d, 0x53, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0f, 0x4d, 0x53, 0x5f, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x4e, 0x74, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x99, 0x04, 0x0a, 0x19, 0x43, 0x53, 0x32, 0x4d, 0x53, 0x5f, 0x53,
	0x65, 0x6e, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6d, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x6d, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x67, 0x6d, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x67, 0x6d, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x76, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c,
	0x76, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x76, 0x45, 0x6e, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x76, 0x45, 0x6e, 0x64, 0x12, 0x26, 0x0a, 0x0e,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0b, 0x66, 0x61, 0x69, 0x6c, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x12, 0x32, 0x0a, 0x08,
	0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0xbb, 0x01, 0x0a, 0x1a, 0x43, 0x53, 0x32, 0x4d, 0x53, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x52,
	0x6f, 0x6c, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x35, 0x0a,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x66, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x0b, 0x66, 0x61, 0x69, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x4f,
	0x0a, 0x17, 0x43, 0x53, 0x32, 0x4d, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22,
	0xa6, 0x01, 0x0a, 0x18, 0x43, 0x53, 0x32, 0x4d, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x64, 0x0a, 0x14, 0x43, 0x53, 0x32, 0x4d,
	0x53, 0x5f, 0x44, 0x65, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x22, 0x6c,
	0x0a, 0x15, 0x43, 0x53, 0x32, 0x4d, 0x53, 0x5f, 0x44, 0x65, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x59, 0x0a, 0x15,
	0x43, 0x53, 0x32, 0x4d, 0x53, 0x5f, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x28, 0x0a,
	0x0f, 0x6d, 0x61, 0x78, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x6d, 0x61, 0x78, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x22, 0x91, 0x01, 0x0a, 0x16, 0x43, 0x53, 0x32, 0x4d,
	0x53, 0x5f, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x61,
	0x78, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0f, 0x6d, 0x61, 0x78, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61,
	0x69, 0x6c, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x71, 0x0a, 0x13, 0x43,
	0x53, 0x32, 0x4d, 0x53, 0x5f, 0x4f, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x42, 0x0a, 0x0a, 0x6d, 0x61,
	0x69, 0x6c, 0x4f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6c,
	0x61, 0x67, 0x52, 0x0a, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x7c,
	0x0a, 0x14, 0x43, 0x53, 0x32, 0x4d, 0x53, 0x5f, 0x4f, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x4c,
	0x0a, 0x0e, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0e, 0x6d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x13, 0x5a, 0x11,
	0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_B_MS_Message_proto_rawDescOnce sync.Once
	file_B_MS_Message_proto_rawDescData = file_B_MS_Message_proto_rawDesc
)

func file_B_MS_Message_proto_rawDescGZIP() []byte {
	file_B_MS_Message_proto_rawDescOnce.Do(func() {
		file_B_MS_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_B_MS_Message_proto_rawDescData)
	})
	return file_B_MS_Message_proto_rawDescData
}

var file_B_MS_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_B_MS_Message_proto_goTypes = []interface{}{
	(*MS_ConnectedNtf)(nil),            // 0: network.message.MS_ConnectedNtf
	(*CS2MS_SendRoleMailRequest)(nil),  // 1: network.message.CS2MS_SendRoleMailRequest
	(*CS2MS_SendRoleMailResponse)(nil), // 2: network.message.CS2MS_SendRoleMailResponse
	(*CS2MS_GetAllMailRequest)(nil),    // 3: network.message.CS2MS_GetAllMailRequest
	(*CS2MS_GetAllMailResponse)(nil),   // 4: network.message.CS2MS_GetAllMailResponse
	(*CS2MS_DelMailRequest)(nil),       // 5: network.message.CS2MS_DelMailRequest
	(*CS2MS_DelMailResponse)(nil),      // 6: network.message.CS2MS_DelMailResponse
	(*CS2MS_SyncMailRequest)(nil),      // 7: network.message.CS2MS_SyncMailRequest
	(*CS2MS_SyncMailResponse)(nil),     // 8: network.message.CS2MS_SyncMailResponse
	(*CS2MS_OpMailRequest)(nil),        // 9: network.message.CS2MS_OpMailRequest
	(*CS2MS_OpMailResponse)(nil),       // 10: network.message.CS2MS_OpMailResponse
	(*Items)(nil),                      // 11: network.message.items
	(Result)(0),                        // 12: network.message.Result
	(*MailInfo)(nil),                   // 13: network.message.MailInfo
	(*MailOperationFlag)(nil),          // 14: network.message.MailOperationFlag
	(*MailOperationResult)(nil),        // 15: network.message.MailOperationResult
}
var file_B_MS_Message_proto_depIdxs = []int32{
	11, // 0: network.message.CS2MS_SendRoleMailRequest.itemList:type_name -> network.message.items
	12, // 1: network.message.CS2MS_SendRoleMailResponse.errorCode:type_name -> network.message.Result
	12, // 2: network.message.CS2MS_GetAllMailResponse.errorCode:type_name -> network.message.Result
	13, // 3: network.message.CS2MS_GetAllMailResponse.mailInfo:type_name -> network.message.MailInfo
	12, // 4: network.message.CS2MS_DelMailResponse.errorCode:type_name -> network.message.Result
	13, // 5: network.message.CS2MS_SyncMailResponse.mailInfo:type_name -> network.message.MailInfo
	14, // 6: network.message.CS2MS_OpMailRequest.mailOpList:type_name -> network.message.MailOperationFlag
	15, // 7: network.message.CS2MS_OpMailResponse.mailResultList:type_name -> network.message.MailOperationResult
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_B_MS_Message_proto_init() }
func file_B_MS_Message_proto_init() {
	if File_B_MS_Message_proto != nil {
		return
	}
	file_BaseInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_B_MS_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MS_ConnectedNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_SendRoleMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_SendRoleMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_GetAllMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_GetAllMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_DelMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_DelMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_SyncMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_SyncMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_OpMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_B_MS_Message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CS2MS_OpMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_B_MS_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_B_MS_Message_proto_goTypes,
		DependencyIndexes: file_B_MS_Message_proto_depIdxs,
		MessageInfos:      file_B_MS_Message_proto_msgTypes,
	}.Build()
	File_B_MS_Message_proto = out.File
	file_B_MS_Message_proto_rawDesc = nil
	file_B_MS_Message_proto_goTypes = nil
	file_B_MS_Message_proto_depIdxs = nil
}
