// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.9.0
// source: CRobot.proto

package network_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//* User登录请求
type C2B_RobotLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId        uint64 `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`
	RobotName      string `protobuf:"bytes,2,opt,name=robotName,proto3" json:"robotName,omitempty"`
	RobotSessionId int32  `protobuf:"varint,3,opt,name=robotSessionId,proto3" json:"robotSessionId,omitempty"`
}

func (x *C2B_RobotLoginRequest) Reset() {
	*x = C2B_RobotLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CRobot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2B_RobotLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2B_RobotLoginRequest) ProtoMessage() {}

func (x *C2B_RobotLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CRobot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2B_RobotLoginRequest.ProtoReflect.Descriptor instead.
func (*C2B_RobotLoginRequest) Descriptor() ([]byte, []int) {
	return file_CRobot_proto_rawDescGZIP(), []int{0}
}

func (x *C2B_RobotLoginRequest) GetRobotId() uint64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *C2B_RobotLoginRequest) GetRobotName() string {
	if x != nil {
		return x.RobotName
	}
	return ""
}

func (x *C2B_RobotLoginRequest) GetRobotSessionId() int32 {
	if x != nil {
		return x.RobotSessionId
	}
	return 0
}

//* User登录回应
type C2B_RobotLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId        uint64 `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`
	RobotSessionId int32  `protobuf:"varint,2,opt,name=robotSessionId,proto3" json:"robotSessionId,omitempty"`
	LoginResult    Result `protobuf:"varint,3,opt,name=loginResult,proto3,enum=network.message.Result" json:"loginResult,omitempty"`
}

func (x *C2B_RobotLoginResponse) Reset() {
	*x = C2B_RobotLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CRobot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2B_RobotLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2B_RobotLoginResponse) ProtoMessage() {}

func (x *C2B_RobotLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CRobot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2B_RobotLoginResponse.ProtoReflect.Descriptor instead.
func (*C2B_RobotLoginResponse) Descriptor() ([]byte, []int) {
	return file_CRobot_proto_rawDescGZIP(), []int{1}
}

func (x *C2B_RobotLoginResponse) GetRobotId() uint64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *C2B_RobotLoginResponse) GetRobotSessionId() int32 {
	if x != nil {
		return x.RobotSessionId
	}
	return 0
}

func (x *C2B_RobotLoginResponse) GetLoginResult() Result {
	if x != nil {
		return x.LoginResult
	}
	return Result_SUCCESS
}

//位置同步
type C2B_StatusSyncPosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId    uint64    `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`
	RoleId     uint64    `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Pos        []float32 `protobuf:"fixed32,3,rep,packed,name=pos,proto3" json:"pos,omitempty"`
	Dir        []float32 `protobuf:"fixed32,4,rep,packed,name=dir,proto3" json:"dir,omitempty"`
	ServerUnix int64     `protobuf:"varint,5,opt,name=serverUnix,proto3" json:"serverUnix,omitempty"`
	SendTime   int64     `protobuf:"varint,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
}

func (x *C2B_StatusSyncPosRequest) Reset() {
	*x = C2B_StatusSyncPosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CRobot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2B_StatusSyncPosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2B_StatusSyncPosRequest) ProtoMessage() {}

func (x *C2B_StatusSyncPosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CRobot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2B_StatusSyncPosRequest.ProtoReflect.Descriptor instead.
func (*C2B_StatusSyncPosRequest) Descriptor() ([]byte, []int) {
	return file_CRobot_proto_rawDescGZIP(), []int{2}
}

func (x *C2B_StatusSyncPosRequest) GetRobotId() uint64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *C2B_StatusSyncPosRequest) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *C2B_StatusSyncPosRequest) GetPos() []float32 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *C2B_StatusSyncPosRequest) GetDir() []float32 {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *C2B_StatusSyncPosRequest) GetServerUnix() int64 {
	if x != nil {
		return x.ServerUnix
	}
	return 0
}

func (x *C2B_StatusSyncPosRequest) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

//位置同步 返回
type C2B_StatusSyncPosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId    uint64    `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`
	RoleId     uint64    `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Pos        []float32 `protobuf:"fixed32,3,rep,packed,name=pos,proto3" json:"pos,omitempty"`
	Dir        []float32 `protobuf:"fixed32,4,rep,packed,name=dir,proto3" json:"dir,omitempty"`
	ServerUnix int64     `protobuf:"varint,5,opt,name=serverUnix,proto3" json:"serverUnix,omitempty"`
	SendTime   int64     `protobuf:"varint,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
}

func (x *C2B_StatusSyncPosResponse) Reset() {
	*x = C2B_StatusSyncPosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CRobot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2B_StatusSyncPosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2B_StatusSyncPosResponse) ProtoMessage() {}

func (x *C2B_StatusSyncPosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CRobot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2B_StatusSyncPosResponse.ProtoReflect.Descriptor instead.
func (*C2B_StatusSyncPosResponse) Descriptor() ([]byte, []int) {
	return file_CRobot_proto_rawDescGZIP(), []int{3}
}

func (x *C2B_StatusSyncPosResponse) GetRobotId() uint64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *C2B_StatusSyncPosResponse) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *C2B_StatusSyncPosResponse) GetPos() []float32 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *C2B_StatusSyncPosResponse) GetDir() []float32 {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *C2B_StatusSyncPosResponse) GetServerUnix() int64 {
	if x != nil {
		return x.ServerUnix
	}
	return 0
}

func (x *C2B_StatusSyncPosResponse) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

//发送技能消息
type C2B_StatusSyncSkillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId    uint64    `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`
	RoleId     uint64    `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	PressType  uint32    `protobuf:"varint,3,opt,name=pressType,proto3" json:"pressType,omitempty"`
	Forward    []float32 `protobuf:"fixed32,4,rep,packed,name=forward,proto3" json:"forward,omitempty"`
	ChaseId    uint64    `protobuf:"varint,5,opt,name=chaseId,proto3" json:"chaseId,omitempty"`
	ServerUnix int64     `protobuf:"varint,6,opt,name=serverUnix,proto3" json:"serverUnix,omitempty"`
	SendTime   int64     `protobuf:"varint,7,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
}

func (x *C2B_StatusSyncSkillRequest) Reset() {
	*x = C2B_StatusSyncSkillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CRobot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2B_StatusSyncSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2B_StatusSyncSkillRequest) ProtoMessage() {}

func (x *C2B_StatusSyncSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CRobot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2B_StatusSyncSkillRequest.ProtoReflect.Descriptor instead.
func (*C2B_StatusSyncSkillRequest) Descriptor() ([]byte, []int) {
	return file_CRobot_proto_rawDescGZIP(), []int{4}
}

func (x *C2B_StatusSyncSkillRequest) GetRobotId() uint64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *C2B_StatusSyncSkillRequest) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *C2B_StatusSyncSkillRequest) GetPressType() uint32 {
	if x != nil {
		return x.PressType
	}
	return 0
}

func (x *C2B_StatusSyncSkillRequest) GetForward() []float32 {
	if x != nil {
		return x.Forward
	}
	return nil
}

func (x *C2B_StatusSyncSkillRequest) GetChaseId() uint64 {
	if x != nil {
		return x.ChaseId
	}
	return 0
}

func (x *C2B_StatusSyncSkillRequest) GetServerUnix() int64 {
	if x != nil {
		return x.ServerUnix
	}
	return 0
}

func (x *C2B_StatusSyncSkillRequest) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

//发送技能消息 返回
type C2B_StatusSyncSkillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId    uint64    `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`
	RoleId     uint64    `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	SkillId    uint32    `protobuf:"varint,3,opt,name=skillId,proto3" json:"skillId,omitempty"`
	Status     uint32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Action     string    `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Flag       uint32    `protobuf:"varint,6,opt,name=flag,proto3" json:"flag,omitempty"`
	ChaseId    uint64    `protobuf:"varint,7,opt,name=chaseId,proto3" json:"chaseId,omitempty"`
	Chasepos   []float32 `protobuf:"fixed32,8,rep,packed,name=Chasepos,proto3" json:"Chasepos,omitempty"`
	ServerUnix int64     `protobuf:"varint,9,opt,name=serverUnix,proto3" json:"serverUnix,omitempty"`
	SendTime   int64     `protobuf:"varint,10,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
}

func (x *C2B_StatusSyncSkillResponse) Reset() {
	*x = C2B_StatusSyncSkillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CRobot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2B_StatusSyncSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2B_StatusSyncSkillResponse) ProtoMessage() {}

func (x *C2B_StatusSyncSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CRobot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2B_StatusSyncSkillResponse.ProtoReflect.Descriptor instead.
func (*C2B_StatusSyncSkillResponse) Descriptor() ([]byte, []int) {
	return file_CRobot_proto_rawDescGZIP(), []int{5}
}

func (x *C2B_StatusSyncSkillResponse) GetRobotId() uint64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *C2B_StatusSyncSkillResponse) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *C2B_StatusSyncSkillResponse) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *C2B_StatusSyncSkillResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *C2B_StatusSyncSkillResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *C2B_StatusSyncSkillResponse) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *C2B_StatusSyncSkillResponse) GetChaseId() uint64 {
	if x != nil {
		return x.ChaseId
	}
	return 0
}

func (x *C2B_StatusSyncSkillResponse) GetChasepos() []float32 {
	if x != nil {
		return x.Chasepos
	}
	return nil
}

func (x *C2B_StatusSyncSkillResponse) GetServerUnix() int64 {
	if x != nil {
		return x.ServerUnix
	}
	return 0
}

func (x *C2B_StatusSyncSkillResponse) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

var File_CRobot_proto protoreflect.FileDescriptor

var file_CRobot_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x43, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x0e, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x77, 0x0a, 0x15, 0x43, 0x32, 0x42, 0x5f, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x16, 0x43, 0x32, 0x42,
	0x5f, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0xac, 0x01, 0x0a, 0x18, 0x43, 0x32, 0x42, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53,
	0x79, 0x6e, 0x63, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x03, 0x70, 0x6f,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x02, 0x52, 0x03,
	0x64, 0x69, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x6e, 0x69,
	0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55,
	0x6e, 0x69, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0xad, 0x01, 0x0a, 0x19, 0x43, 0x32, 0x42, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x79,
	0x6e, 0x63, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x03, 0x70, 0x6f,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x02, 0x52, 0x03,
	0x64, 0x69, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x6e, 0x69,
	0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55,
	0x6e, 0x69, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0xdc, 0x01, 0x0a, 0x1a, 0x43, 0x32, 0x42, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x79,
	0x6e, 0x63, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x07, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x78,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x6e,
	0x69, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x9f,
	0x02, 0x0a, 0x1b, 0x43, 0x32, 0x42, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x79, 0x6e,
	0x63, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x73, 0x65, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x73,
	0x65, 0x70, 0x6f, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x02, 0x52, 0x08, 0x43, 0x68, 0x61, 0x73,
	0x65, 0x70, 0x6f, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x6e,
	0x69, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x55, 0x6e, 0x69, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CRobot_proto_rawDescOnce sync.Once
	file_CRobot_proto_rawDescData = file_CRobot_proto_rawDesc
)

func file_CRobot_proto_rawDescGZIP() []byte {
	file_CRobot_proto_rawDescOnce.Do(func() {
		file_CRobot_proto_rawDescData = protoimpl.X.CompressGZIP(file_CRobot_proto_rawDescData)
	})
	return file_CRobot_proto_rawDescData
}

var file_CRobot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_CRobot_proto_goTypes = []interface{}{
	(*C2B_RobotLoginRequest)(nil),       // 0: network.message.C2B_RobotLoginRequest
	(*C2B_RobotLoginResponse)(nil),      // 1: network.message.C2B_RobotLoginResponse
	(*C2B_StatusSyncPosRequest)(nil),    // 2: network.message.C2B_StatusSyncPosRequest
	(*C2B_StatusSyncPosResponse)(nil),   // 3: network.message.C2B_StatusSyncPosResponse
	(*C2B_StatusSyncSkillRequest)(nil),  // 4: network.message.C2B_StatusSyncSkillRequest
	(*C2B_StatusSyncSkillResponse)(nil), // 5: network.message.C2B_StatusSyncSkillResponse
	(Result)(0),                         // 6: network.message.Result
}
var file_CRobot_proto_depIdxs = []int32{
	6, // 0: network.message.C2B_RobotLoginResponse.loginResult:type_name -> network.message.Result
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CRobot_proto_init() }
func file_CRobot_proto_init() {
	if File_CRobot_proto != nil {
		return
	}
	file_BaseInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CRobot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2B_RobotLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CRobot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2B_RobotLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CRobot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2B_StatusSyncPosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CRobot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2B_StatusSyncPosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CRobot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2B_StatusSyncSkillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CRobot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2B_StatusSyncSkillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CRobot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CRobot_proto_goTypes,
		DependencyIndexes: file_CRobot_proto_depIdxs,
		MessageInfos:      file_CRobot_proto_msgTypes,
	}.Build()
	File_CRobot_proto = out.File
	file_CRobot_proto_rawDesc = nil
	file_CRobot_proto_goTypes = nil
	file_CRobot_proto_depIdxs = nil
}
